/**
 * Auto-generated database field constants (Frontend)
 * Generated to match backend DatabaseFields.php
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Update backend constants and regenerate this file
 */

// ============================================
// TABLE FIELD CONSTANTS
// ============================================

/**
 * CLIENTS table fields
 */
export const CLIENTS = {
  ID: "id",
  ORGANISATION_NAME: "organisation_name",
  CAC_REGISTRATION_NUMBER: "cac_registration_number",
  SLUG: "slug",
  PREFIX: "prefix",
  HEAD_OFFICE_ADDRESS: "head_office_address",
  PHONE: "phone",
  INDUSTRY_CATEGORY: "industry_category",
  CLIENT_CATEGORY: "client_category",
  PAY_CALCULATION_BASIS: "pay_calculation_basis",
  STATUS: "status",
  CREATED_AT: "created_at",
  UPDATED_AT: "updated_at",
};

/**
 * STAFF table fields
 */
export const STAFF = {
  ID: "id",
  CANDIDATE_ID: "candidate_id",
  CLIENT_ID: "client_id",
  SERVICE_LOCATION_ID: "service_location_id",
  STAFF_TYPE_ID: "staff_type_id",
  EMPLOYEE_CODE: "employee_code",
  STAFF_ID: "staff_id",
  EMAIL: "email",
  FIRST_NAME: "first_name",
  MIDDLE_NAME: "middle_name",
  LAST_NAME: "last_name",
  GENDER: "gender",
  ENTRY_DATE: "entry_date",
  END_DATE: "end_date",
  APPOINTMENT_STATUS: "appointment_status",
  EMPLOYMENT_TYPE: "employment_type",
  STATUS: "status",
  PAY_GRADE_STRUCTURE_ID: "pay_grade_structure_id",
  SALARY_EFFECTIVE_DATE: "salary_effective_date",
  SALARY_CURRENCY: "salary_currency",
  JOB_TITLE: "job_title",
  DEPARTMENT: "department",
  LOCATION: "location",
  STATE_LGA_ID: "state_lga_id",
  SUPERVISOR_ID: "supervisor_id",
  LEAVE_CATEGORY_LEVEL: "leave_category_level",
  APPRAISAL_CATEGORY: "appraisal_category",
  TAX_ID_NO: "tax_id_no",
  PF_NO: "pf_no",
  PF_ADMINISTRATOR: "pf_administrator",
  PFA_CODE: "pfa_code",
  BV_NO: "bv_no",
  NHF_ACCOUNT_NO: "nhf_account_no",
  CLIENT_ASSIGNED_CODE: "client_assigned_code",
  DEPLOYMENT_CODE: "deployment_code",
  ONBOARDING_METHOD: "onboarding_method",
  ONBOARDED_BY: "onboarded_by",
  CUSTOM_FIELDS: "custom_fields",
  CREATED_AT: "created_at",
  UPDATED_AT: "updated_at",
};

/**
 * RECRUITMENT_REQUESTS table fields
 */
export const RECRUITMENT_REQUESTS = {
  ID: "id",
  CLIENT_ID: "client_id",
  TICKET_ID: "ticket_id",
  JOB_STRUCTURE_ID: "job_structure_id",
  SERVICE_LOCATION_ID: "service_location_id",
  JOB_TITLE: "job_title",
  DEPARTMENT: "department",
  NUMBER_OF_VACANCIES: "number_of_vacancies",
  STAFF_ACCEPTED_OFFER: "staff_accepted_offer",
  STATUS: "status",
  CREATED_AT: "created_at",
  UPDATED_AT: "updated_at",
};

/**
 * PAY_GRADE_STRUCTURES table fields
 */
export const PAY_GRADE_STRUCTURES = {
  ID: "id",
  CLIENT_ID: "client_id",
  JOB_STRUCTURE_ID: "job_structure_id",
  GRADE_NAME: "grade_name",
  GRADE_CODE: "grade_code",
  LEVEL: "level",
  STEP: "step",
  PAY_STRUCTURE_TYPE: "pay_structure_type",
  BASIC_SALARY: "basic_salary",
  TRANSPORT_ALLOWANCE: "transport_allowance",
  HOUSING_ALLOWANCE: "housing_allowance",
  MEAL_ALLOWANCE: "meal_allowance",
  EMOLUMENTS: "emoluments",
  TOTAL_COMPENSATION: "total_compensation",
  CURRENCY: "currency",
  IS_ACTIVE: "is_active",
  CREATED_AT: "created_at",
  UPDATED_AT: "updated_at",
};

/**
 * JOB_STRUCTURES table fields
 */
export const JOB_STRUCTURES = {
  ID: "id",
  CLIENT_ID: "client_id",
  JOB_TITLE: "job_title",
  JOB_DESCRIPTION: "job_description",
  CREATED_AT: "created_at",
  UPDATED_AT: "updated_at",
};

// ============================================
// ENUM VALUE CONSTANTS
// ============================================

/**
 * CLIENTS_STATUS enum values
 */
export const CLIENTS_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  SUSPENDED: "suspended",
};

/**
 * CLIENTS_PAY_CALCULATION_BASIS enum values
 */
export const CLIENTS_PAY_CALCULATION_BASIS = {
  WORKING_DAYS: "working_days",
  CALENDAR_DAYS: "calendar_days",
};

/**
 * STAFF_GENDER enum values
 */
export const STAFF_GENDER = {
  MALE: "male",
  FEMALE: "female",
  OTHER: "other",
};

/**
 * STAFF_APPOINTMENT_STATUS enum values
 */
export const STAFF_APPOINTMENT_STATUS = {
  PROBATION: "probation",
  CONFIRMED: "confirmed",
  CONTRACT: "contract",
  TEMPORARY: "temporary",
};

/**
 * STAFF_EMPLOYMENT_TYPE enum values
 */
export const STAFF_EMPLOYMENT_TYPE = {
  FULL_TIME: "full_time",
  PART_TIME: "part_time",
  CONTRACT: "contract",
  TEMPORARY: "temporary",
  INTERNSHIP: "internship",
};

/**
 * STAFF_STATUS enum values
 */
export const STAFF_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  TERMINATED: "terminated",
  SUSPENDED: "suspended",
};

/**
 * STAFF_ONBOARDING_METHOD enum values
 */
export const STAFF_ONBOARDING_METHOD = {
  FROM_CANDIDATE: "from_candidate",
  MANUAL_ENTRY: "manual_entry",
  BULK_UPLOAD: "bulk_upload",
};

// ============================================
// API RESPONSE FIELD MAPPINGS
// ============================================

/**
 * API Response field mappings for data transformation
 */
export const API_RESPONSE_FIELDS = {
  CLIENT: {
    id: CLIENTS.ID,
    client_name: CLIENTS.ORGANISATION_NAME,
    organisation_name: CLIENTS.ORGANISATION_NAME,
    prefix: CLIENTS.PREFIX,
    status: CLIENTS.STATUS,
    active_tickets: "active_tickets", // Calculated field
  },
  STAFF: {
    id: STAFF.ID,
    employee_code: STAFF.EMPLOYEE_CODE,
    first_name: STAFF.FIRST_NAME,
    last_name: STAFF.LAST_NAME,
    email: STAFF.EMAIL,
    client_id: STAFF.CLIENT_ID,
    pay_grade_structure_id: STAFF.PAY_GRADE_STRUCTURE_ID,
    full_name: "full_name", // Calculated field
    remaining_positions: "remaining_positions", // Calculated field
  },
  RECRUITMENT_REQUEST: {
    id: RECRUITMENT_REQUESTS.ID,
    ticket_code: RECRUITMENT_REQUESTS.TICKET_ID,
    job_title: RECRUITMENT_REQUESTS.JOB_TITLE,
    department: RECRUITMENT_REQUESTS.DEPARTMENT,
    total_positions: RECRUITMENT_REQUESTS.NUMBER_OF_VACANCIES,
    filled_positions: RECRUITMENT_REQUESTS.STAFF_ACCEPTED_OFFER,
    available_slots: "available_slots", // Calculated field
    job_structure_id: RECRUITMENT_REQUESTS.JOB_STRUCTURE_ID,
  },
  PAY_GRADE: {
    id: PAY_GRADE_STRUCTURES.ID,
    grade_name: PAY_GRADE_STRUCTURES.GRADE_NAME,
    grade_code: PAY_GRADE_STRUCTURES.GRADE_CODE,
    basic_salary: PAY_GRADE_STRUCTURES.BASIC_SALARY,
    housing_allowance: PAY_GRADE_STRUCTURES.HOUSING_ALLOWANCE,
    transport_allowance: PAY_GRADE_STRUCTURES.TRANSPORT_ALLOWANCE,
    meal_allowance: PAY_GRADE_STRUCTURES.MEAL_ALLOWANCE,
    total_compensation: PAY_GRADE_STRUCTURES.TOTAL_COMPENSATION,
    currency: PAY_GRADE_STRUCTURES.CURRENCY,
    emoluments: PAY_GRADE_STRUCTURES.EMOLUMENTS,
    pay_structure_type: PAY_GRADE_STRUCTURES.PAY_STRUCTURE_TYPE,
  },
};

// ============================================
// FORM FIELD CONSTANTS
// ============================================

/**
 * Form field constants for UI components
 */
export const FORM_FIELDS = {
  MANUAL_BOARDING: {
    // Client Selection
    CLIENT_ID: "client_id",

    // Ticket Selection
    RECRUITMENT_REQUEST_ID: "recruitment_request_id",

    // Staff Information
    FIRST_NAME: "first_name",
    MIDDLE_NAME: "middle_name",
    LAST_NAME: "last_name",
    EMAIL: "email",
    GENDER: "gender",
    ENTRY_DATE: "entry_date",
    APPOINTMENT_STATUS: "appointment_status",
    EMPLOYMENT_TYPE: "employment_type",
    JOB_TITLE: "job_title",
    DEPARTMENT: "department",

    // Pay Information
    PAY_GRADE_STRUCTURE_ID: "pay_grade_structure_id",

    // Optional Fields
    PHONE: "phone",
    LOCATION: "location",
    TAX_ID_NO: "tax_id_no",
    PF_NO: "pf_no",

    // Meta Fields
    ONBOARDING_METHOD: "onboarding_method",
    NOTES: "notes",
  },
};

// ============================================
// VALIDATION RULES
// ============================================

/**
 * Field validation rules
 */
export const VALIDATION_RULES = {
  REQUIRED_FIELDS: [
    FORM_FIELDS.MANUAL_BOARDING.CLIENT_ID,
    FORM_FIELDS.MANUAL_BOARDING.RECRUITMENT_REQUEST_ID,
    FORM_FIELDS.MANUAL_BOARDING.FIRST_NAME,
    FORM_FIELDS.MANUAL_BOARDING.LAST_NAME,
    FORM_FIELDS.MANUAL_BOARDING.EMAIL,
    FORM_FIELDS.MANUAL_BOARDING.GENDER,
    FORM_FIELDS.MANUAL_BOARDING.ENTRY_DATE,
    FORM_FIELDS.MANUAL_BOARDING.PAY_GRADE_STRUCTURE_ID,
  ],

  OPTIONAL_FIELDS: [
    FORM_FIELDS.MANUAL_BOARDING.MIDDLE_NAME,
    FORM_FIELDS.MANUAL_BOARDING.PHONE,
    FORM_FIELDS.MANUAL_BOARDING.LOCATION,
    FORM_FIELDS.MANUAL_BOARDING.TAX_ID_NO,
    FORM_FIELDS.MANUAL_BOARDING.PF_NO,
    FORM_FIELDS.MANUAL_BOARDING.NOTES,
  ],

  EMAIL_PATTERN: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE_PATTERN: /^[\+]?[1-9][\d]{0,15}$/,
};

// ============================================
// EXCEL TEMPLATE HEADERS
// ============================================

/**
 * Excel template column headers for bulk upload
 */
export const EXCEL_HEADERS = {
  MANUAL_BOARDING: {
    FIRST_NAME: "First Name",
    MIDDLE_NAME: "Middle Name",
    LAST_NAME: "Last Name",
    EMAIL: "Email",
    ENTRY_DATE: "Entry Date",
    GENDER: "Gender",
    JOB_TITLE: "Job Title",
    DEPARTMENT: "Department",
    APPOINTMENT_STATUS: "Appointment Status",
    EMPLOYMENT_TYPE: "Employment Type",
  },
};

// ============================================
// DEFAULT VALUES
// ============================================

/**
 * Default values for form fields
 */
export const DEFAULTS = {
  STAFF_APPOINTMENT_STATUS: STAFF_APPOINTMENT_STATUS.PROBATION,
  STAFF_EMPLOYMENT_TYPE: STAFF_EMPLOYMENT_TYPE.FULL_TIME,
  STAFF_STATUS: STAFF_STATUS.ACTIVE,
  STAFF_SALARY_CURRENCY: "NGN",
  ONBOARDING_METHOD_MANUAL: STAFF_ONBOARDING_METHOD.MANUAL_ENTRY,
  ONBOARDING_METHOD_BULK: STAFF_ONBOARDING_METHOD.BULK_UPLOAD,
};

// ============================================
// LEGACY COMPATIBILITY (DEPRECATED)
// ============================================

/**
 * @deprecated Use individual exports instead
 * Kept for backward compatibility during migration
 */
export const DB_FIELDS = {
  STAFF,
  CLIENTS,
  RECRUITMENT_REQUESTS,
  PAY_GRADE_STRUCTURES,
  JOB_STRUCTURES,
};

/**
 * @deprecated Use API_RESPONSE_FIELDS instead
 */
export const API_FIELDS = API_RESPONSE_FIELDS;

/**
 * @deprecated Use individual enum exports instead
 */
export const ENUMS = {
  STAFF_GENDER: Object.values(STAFF_GENDER),
  STAFF_APPOINTMENT_STATUS: Object.values(STAFF_APPOINTMENT_STATUS),
  STAFF_EMPLOYMENT_TYPE: Object.values(STAFF_EMPLOYMENT_TYPE),
  STAFF_STATUS: Object.values(STAFF_STATUS),
  STAFF_ONBOARDING_METHOD: Object.values(STAFF_ONBOARDING_METHOD),
  RECRUITMENT_STATUS: ["active", "closed", "cancelled", "on_hold"],
};

// Default export for backward compatibility
export default {
  DB_FIELDS,
  API_FIELDS,
  FORM_FIELDS,
  ENUMS,
  DEFAULTS,
  EXCEL_HEADERS,
  // New structured exports
  CLIENTS,
  STAFF,
  RECRUITMENT_REQUESTS,
  PAY_GRADE_STRUCTURES,
  JOB_STRUCTURES,
  API_RESPONSE_FIELDS,
  VALIDATION_RULES,
};
