<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MissingStatesLgasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Adds missing states and LGAs for:
     * - Adamawa (21 LGAs)
     * - Bauchi (20 LGAs)
     * - Borno (27 LGAs)
     * - Gombe (11 LGAs)
     * - Jigawa (27 LGAs)
     * - Kaduna (23 LGAs)
     * - Kano (44 LGAs)
     * - Katsina (34 LGAs)
     * - Kebbi (21 LGAs)
     * - Sokoto (23 LGAs)
     * - Taraba (16 LGAs)
     * - Yobe (17 LGAs)
     * - Zamfara (14 LGAs)
     */
    public function run()
    {
        $data = [
            // Adamawa State (21 LGAs)
            ['id' => 477, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Demsa', 'lga_code' => 'AD01', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 478, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Fufore', 'lga_code' => 'AD02', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 479, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Ganye', 'lga_code' => 'AD03', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 480, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Girei', 'lga_code' => 'AD04', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 481, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Gombi', 'lga_code' => 'AD05', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 482, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Guyuk', 'lga_code' => 'AD06', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 483, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Hong', 'lga_code' => 'AD07', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 484, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Jada', 'lga_code' => 'AD08', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 485, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Lamurde', 'lga_code' => 'AD09', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 486, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Madagali', 'lga_code' => 'AD10', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 487, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Maiha', 'lga_code' => 'AD11', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 488, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Mayo-Belwa', 'lga_code' => 'AD12', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 489, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Michika', 'lga_code' => 'AD13', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 490, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Mubi North', 'lga_code' => 'AD14', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 491, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Mubi South', 'lga_code' => 'AD15', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 492, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Numan', 'lga_code' => 'AD16', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 493, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Shelleng', 'lga_code' => 'AD17', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 494, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Song', 'lga_code' => 'AD18', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 495, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Toungo', 'lga_code' => 'AD19', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 496, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Yola North', 'lga_code' => 'AD20', 'zone' => 'north_east', 'is_capital' => 1],
            ['id' => 497, 'state_name' => 'Adamawa', 'state_code' => 'AD', 'lga_name' => 'Yola South', 'lga_code' => 'AD21', 'zone' => 'north_east', 'is_capital' => 1],

            // Bauchi State (20 LGAs)
            ['id' => 498, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Alkaleri', 'lga_code' => 'BA01', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 499, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Bauchi', 'lga_code' => 'BA02', 'zone' => 'north_east', 'is_capital' => 1],
            ['id' => 500, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Bogoro', 'lga_code' => 'BA03', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 501, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Dambam', 'lga_code' => 'BA04', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 502, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Darazo', 'lga_code' => 'BA05', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 503, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Dass', 'lga_code' => 'BA06', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 504, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Gamawa', 'lga_code' => 'BA07', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 505, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Ganjuwa', 'lga_code' => 'BA08', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 506, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Giade', 'lga_code' => 'BA09', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 507, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Itas/Gadau', 'lga_code' => 'BA10', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 508, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Jama\'are', 'lga_code' => 'BA11', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 509, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Katagum', 'lga_code' => 'BA12', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 510, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Kirfi', 'lga_code' => 'BA13', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 511, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Misau', 'lga_code' => 'BA14', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 512, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Ningi', 'lga_code' => 'BA15', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 513, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Shira', 'lga_code' => 'BA16', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 514, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Tafawa Balewa', 'lga_code' => 'BA17', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 515, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Toro', 'lga_code' => 'BA18', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 516, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Warji', 'lga_code' => 'BA19', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 517, 'state_name' => 'Bauchi', 'state_code' => 'BA', 'lga_name' => 'Zaki', 'lga_code' => 'BA20', 'zone' => 'north_east', 'is_capital' => 0],

            // Borno State (27 LGAs)
            ['id' => 518, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Abadam', 'lga_code' => 'BO01', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 519, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Askira/Uba', 'lga_code' => 'BO02', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 520, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Bama', 'lga_code' => 'BO03', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 521, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Bayo', 'lga_code' => 'BO04', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 522, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Biu', 'lga_code' => 'BO05', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 523, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Chibok', 'lga_code' => 'BO06', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 524, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Damboa', 'lga_code' => 'BO07', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 525, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Dikwa', 'lga_code' => 'BO08', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 526, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Gubio', 'lga_code' => 'BO09', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 527, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Guzamala', 'lga_code' => 'BO10', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 528, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Gwoza', 'lga_code' => 'BO11', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 529, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Hawul', 'lga_code' => 'BO12', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 530, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Jere', 'lga_code' => 'BO13', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 531, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Kaga', 'lga_code' => 'BO14', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 532, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Kala/Balge', 'lga_code' => 'BO15', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 533, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Konduga', 'lga_code' => 'BO16', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 534, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Kukawa', 'lga_code' => 'BO17', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 535, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Kwaya Kusar', 'lga_code' => 'BO18', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 536, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Mafa', 'lga_code' => 'BO19', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 537, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Magumeri', 'lga_code' => 'BO20', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 538, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Maiduguri', 'lga_code' => 'BO21', 'zone' => 'north_east', 'is_capital' => 1],
            ['id' => 539, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Marte', 'lga_code' => 'BO22', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 540, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Mobbar', 'lga_code' => 'BO23', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 541, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Monguno', 'lga_code' => 'BO24', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 542, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Ngala', 'lga_code' => 'BO25', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 543, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Nganzai', 'lga_code' => 'BO26', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 544, 'state_name' => 'Borno', 'state_code' => 'BO', 'lga_name' => 'Shani', 'lga_code' => 'BO27', 'zone' => 'north_east', 'is_capital' => 0],

            // Gombe State (11 LGAs)
            ['id' => 545, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Akko', 'lga_code' => 'GO01', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 546, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Balanga', 'lga_code' => 'GO02', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 547, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Billiri', 'lga_code' => 'GO03', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 548, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Dukku', 'lga_code' => 'GO04', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 549, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Funakaye', 'lga_code' => 'GO05', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 550, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Gombe', 'lga_code' => 'GO06', 'zone' => 'north_east', 'is_capital' => 1],
            ['id' => 551, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Kaltungo', 'lga_code' => 'GO07', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 552, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Kwami', 'lga_code' => 'GO08', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 553, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Nafada', 'lga_code' => 'GO09', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 554, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Shongom', 'lga_code' => 'GO10', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 555, 'state_name' => 'Gombe', 'state_code' => 'GO', 'lga_name' => 'Yamaltu Deba', 'lga_code' => 'GO11', 'zone' => 'north_east', 'is_capital' => 0],

            // Jigawa State (27 LGAs) - continuing...
            ['id' => 556, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Auyo', 'lga_code' => 'JI01', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 557, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Babura', 'lga_code' => 'JI02', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 558, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Biriniwa', 'lga_code' => 'JI03', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 559, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Birnin Kudu', 'lga_code' => 'JI04', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 560, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Buji', 'lga_code' => 'JI05', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 561, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Dutse', 'lga_code' => 'JI06', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 562, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Gagarawa', 'lga_code' => 'JI07', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 563, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Garki', 'lga_code' => 'JI08', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 564, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Gumel', 'lga_code' => 'JI09', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 565, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Guri', 'lga_code' => 'JI10', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 566, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Gwaram', 'lga_code' => 'JI11', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 567, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Gwiwa', 'lga_code' => 'JI12', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 568, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Hadejia', 'lga_code' => 'JI13', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 569, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Jahun', 'lga_code' => 'JI14', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 570, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Kafin Hausa', 'lga_code' => 'JI15', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 571, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Kaugama', 'lga_code' => 'JI16', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 572, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Kazaure', 'lga_code' => 'JI17', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 573, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Kiri Kasama', 'lga_code' => 'JI18', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 574, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Kiyawa', 'lga_code' => 'JI19', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 575, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Maigatari', 'lga_code' => 'JI20', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 576, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Malam Madori', 'lga_code' => 'JI21', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 577, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Miga', 'lga_code' => 'JI22', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 578, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Ringim', 'lga_code' => 'JI23', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 579, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Roni', 'lga_code' => 'JI24', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 580, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Sule Tankarkar', 'lga_code' => 'JI25', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 581, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Taura', 'lga_code' => 'JI26', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 582, 'state_name' => 'Jigawa', 'state_code' => 'JI', 'lga_name' => 'Yankwashi', 'lga_code' => 'JI27', 'zone' => 'north_west', 'is_capital' => 0],

            // Kaduna State (23 LGAs)
            ['id' => 583, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Birnin Gwari', 'lga_code' => 'KD01', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 584, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Chikun', 'lga_code' => 'KD02', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 585, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Giwa', 'lga_code' => 'KD03', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 586, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Igabi', 'lga_code' => 'KD04', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 587, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Ikara', 'lga_code' => 'KD05', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 588, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Jaba', 'lga_code' => 'KD06', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 589, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Jema\'a', 'lga_code' => 'KD07', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 590, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kachia', 'lga_code' => 'KD08', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 591, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kaduna North', 'lga_code' => 'KD09', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 592, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kaduna South', 'lga_code' => 'KD10', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 593, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kagarko', 'lga_code' => 'KD11', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 594, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kajuru', 'lga_code' => 'KD12', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 595, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kaura', 'lga_code' => 'KD13', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 596, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kauru', 'lga_code' => 'KD14', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 597, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kubau', 'lga_code' => 'KD15', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 598, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Kudan', 'lga_code' => 'KD16', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 599, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Lere', 'lga_code' => 'KD17', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 600, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Makarfi', 'lga_code' => 'KD18', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 601, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Sabon Gari', 'lga_code' => 'KD19', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 602, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Sanga', 'lga_code' => 'KD20', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 603, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Soba', 'lga_code' => 'KD21', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 604, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Zangon Kataf', 'lga_code' => 'KD22', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 605, 'state_name' => 'Kaduna', 'state_code' => 'KD', 'lga_name' => 'Zaria', 'lga_code' => 'KD23', 'zone' => 'north_west', 'is_capital' => 0],

            // Kano State (44 LGAs)
            ['id' => 606, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Ajingi', 'lga_code' => 'KN01', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 607, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Albasu', 'lga_code' => 'KN02', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 608, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Bagwai', 'lga_code' => 'KN03', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 609, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Bebeji', 'lga_code' => 'KN04', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 610, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Bichi', 'lga_code' => 'KN05', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 611, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Bunkure', 'lga_code' => 'KN06', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 612, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Dala', 'lga_code' => 'KN07', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 613, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Dambatta', 'lga_code' => 'KN08', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 614, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Dawakin Kudu', 'lga_code' => 'KN09', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 615, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Dawakin Tofa', 'lga_code' => 'KN10', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 616, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Doguwa', 'lga_code' => 'KN11', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 617, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Fagge', 'lga_code' => 'KN12', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 618, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Gabasawa', 'lga_code' => 'KN13', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 619, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Garko', 'lga_code' => 'KN14', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 620, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Garun Mallam', 'lga_code' => 'KN15', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 621, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Gaya', 'lga_code' => 'KN16', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 622, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Gezawa', 'lga_code' => 'KN17', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 623, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Gwale', 'lga_code' => 'KN18', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 624, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Gwarzo', 'lga_code' => 'KN19', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 625, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Kabo', 'lga_code' => 'KN20', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 626, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Kano Municipal', 'lga_code' => 'KN21', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 627, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Karaye', 'lga_code' => 'KN22', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 628, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Kibiya', 'lga_code' => 'KN23', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 629, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Kiru', 'lga_code' => 'KN24', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 630, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Kumbotso', 'lga_code' => 'KN25', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 631, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Kunchi', 'lga_code' => 'KN26', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 632, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Kura', 'lga_code' => 'KN27', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 633, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Madobi', 'lga_code' => 'KN28', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 634, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Makoda', 'lga_code' => 'KN29', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 635, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Minjibir', 'lga_code' => 'KN30', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 636, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Nasarawa', 'lga_code' => 'KN31', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 637, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Rano', 'lga_code' => 'KN32', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 638, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Rimin Gado', 'lga_code' => 'KN33', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 639, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Rogo', 'lga_code' => 'KN34', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 640, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Shanono', 'lga_code' => 'KN35', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 641, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Sumaila', 'lga_code' => 'KN36', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 642, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Takai', 'lga_code' => 'KN37', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 643, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Tarauni', 'lga_code' => 'KN38', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 644, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Tofa', 'lga_code' => 'KN39', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 645, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Tsanyawa', 'lga_code' => 'KN40', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 646, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Tudun Wada', 'lga_code' => 'KN41', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 647, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Ungogo', 'lga_code' => 'KN42', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 648, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Warawa', 'lga_code' => 'KN43', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 649, 'state_name' => 'Kano', 'state_code' => 'KN', 'lga_name' => 'Wudil', 'lga_code' => 'KN44', 'zone' => 'north_west', 'is_capital' => 0],

            // Katsina State (34 LGAs)
            ['id' => 650, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Bakori', 'lga_code' => 'KT01', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 651, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Batagarawa', 'lga_code' => 'KT02', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 652, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Batsari', 'lga_code' => 'KT03', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 653, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Baure', 'lga_code' => 'KT04', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 654, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Bindawa', 'lga_code' => 'KT05', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 655, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Charanchi', 'lga_code' => 'KT06', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 656, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Dandume', 'lga_code' => 'KT07', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 657, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Danja', 'lga_code' => 'KT08', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 658, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Dan Musa', 'lga_code' => 'KT09', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 659, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Daura', 'lga_code' => 'KT10', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 660, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Dutsi', 'lga_code' => 'KT11', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 661, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Dutsin Ma', 'lga_code' => 'KT12', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 662, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Faskari', 'lga_code' => 'KT13', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 663, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Funtua', 'lga_code' => 'KT14', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 664, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Ingawa', 'lga_code' => 'KT15', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 665, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Jibia', 'lga_code' => 'KT16', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 666, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Kafur', 'lga_code' => 'KT17', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 667, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Kaita', 'lga_code' => 'KT18', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 668, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Kankara', 'lga_code' => 'KT19', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 669, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Kankia', 'lga_code' => 'KT20', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 670, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Katsina', 'lga_code' => 'KT21', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 671, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Kurfi', 'lga_code' => 'KT22', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 672, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Kusada', 'lga_code' => 'KT23', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 673, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Mai\'Adua', 'lga_code' => 'KT24', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 674, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Malumfashi', 'lga_code' => 'KT25', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 675, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Mani', 'lga_code' => 'KT26', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 676, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Mashi', 'lga_code' => 'KT27', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 677, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Matazu', 'lga_code' => 'KT28', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 678, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Musawa', 'lga_code' => 'KT29', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 679, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Rimi', 'lga_code' => 'KT30', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 680, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Sabuwa', 'lga_code' => 'KT31', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 681, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Safana', 'lga_code' => 'KT32', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 682, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Sandamu', 'lga_code' => 'KT33', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 683, 'state_name' => 'Katsina', 'state_code' => 'KT', 'lga_name' => 'Zango', 'lga_code' => 'KT34', 'zone' => 'north_west', 'is_capital' => 0],

            // Kebbi State (21 LGAs)
            ['id' => 684, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Aleiro', 'lga_code' => 'KE01', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 685, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Arewa Dandi', 'lga_code' => 'KE02', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 686, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Argungu', 'lga_code' => 'KE03', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 687, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Augie', 'lga_code' => 'KE04', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 688, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Bagudo', 'lga_code' => 'KE05', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 689, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Birnin Kebbi', 'lga_code' => 'KE06', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 690, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Bunza', 'lga_code' => 'KE07', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 691, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Dandi', 'lga_code' => 'KE08', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 692, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Fakai', 'lga_code' => 'KE09', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 693, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Gwandu', 'lga_code' => 'KE10', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 694, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Jega', 'lga_code' => 'KE11', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 695, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Kalgo', 'lga_code' => 'KE12', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 696, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Koko/Besse', 'lga_code' => 'KE13', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 697, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Maiyama', 'lga_code' => 'KE14', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 698, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Ngaski', 'lga_code' => 'KE15', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 699, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Sakaba', 'lga_code' => 'KE16', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 700, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Shanga', 'lga_code' => 'KE17', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 701, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Suru', 'lga_code' => 'KE18', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 702, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Wasagu/Danko', 'lga_code' => 'KE19', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 703, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Yauri', 'lga_code' => 'KE20', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 704, 'state_name' => 'Kebbi', 'state_code' => 'KE', 'lga_name' => 'Zuru', 'lga_code' => 'KE21', 'zone' => 'north_west', 'is_capital' => 0],

            // Sokoto State (23 LGAs)
            ['id' => 705, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Binji', 'lga_code' => 'SO01', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 706, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Bodinga', 'lga_code' => 'SO02', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 707, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Dange Shuni', 'lga_code' => 'SO03', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 708, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Gada', 'lga_code' => 'SO04', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 709, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Goronyo', 'lga_code' => 'SO05', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 710, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Gudu', 'lga_code' => 'SO06', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 711, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Gwadabawa', 'lga_code' => 'SO07', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 712, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Illela', 'lga_code' => 'SO08', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 713, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Isa', 'lga_code' => 'SO09', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 714, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Kebbe', 'lga_code' => 'SO10', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 715, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Kware', 'lga_code' => 'SO11', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 716, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Rabah', 'lga_code' => 'SO12', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 717, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Sabon Birni', 'lga_code' => 'SO13', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 718, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Shagari', 'lga_code' => 'SO14', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 719, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Silame', 'lga_code' => 'SO15', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 720, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Sokoto North', 'lga_code' => 'SO16', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 721, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Sokoto South', 'lga_code' => 'SO17', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 722, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Tambuwal', 'lga_code' => 'SO18', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 723, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Tangaza', 'lga_code' => 'SO19', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 724, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Tureta', 'lga_code' => 'SO20', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 725, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Wamako', 'lga_code' => 'SO21', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 726, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Wurno', 'lga_code' => 'SO22', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 727, 'state_name' => 'Sokoto', 'state_code' => 'SO', 'lga_name' => 'Yabo', 'lga_code' => 'SO23', 'zone' => 'north_west', 'is_capital' => 0],

            // Taraba State (16 LGAs)
            ['id' => 728, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Ardo Kola', 'lga_code' => 'TA01', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 729, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Bali', 'lga_code' => 'TA02', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 730, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Donga', 'lga_code' => 'TA03', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 731, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Gashaka', 'lga_code' => 'TA04', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 732, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Gassol', 'lga_code' => 'TA05', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 733, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Ibi', 'lga_code' => 'TA06', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 734, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Jalingo', 'lga_code' => 'TA07', 'zone' => 'north_east', 'is_capital' => 1],
            ['id' => 735, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Karim Lamido', 'lga_code' => 'TA08', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 736, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Kurmi', 'lga_code' => 'TA09', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 737, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Lau', 'lga_code' => 'TA10', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 738, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Sardauna', 'lga_code' => 'TA11', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 739, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Takum', 'lga_code' => 'TA12', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 740, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Ussa', 'lga_code' => 'TA13', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 741, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Wukari', 'lga_code' => 'TA14', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 742, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Yorro', 'lga_code' => 'TA15', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 743, 'state_name' => 'Taraba', 'state_code' => 'TA', 'lga_name' => 'Zing', 'lga_code' => 'TA16', 'zone' => 'north_east', 'is_capital' => 0],

            // Yobe State (17 LGAs)
            ['id' => 744, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Bade', 'lga_code' => 'YO01', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 745, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Bursari', 'lga_code' => 'YO02', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 746, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Damaturu', 'lga_code' => 'YO03', 'zone' => 'north_east', 'is_capital' => 1],
            ['id' => 747, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Fika', 'lga_code' => 'YO04', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 748, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Fune', 'lga_code' => 'YO05', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 749, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Geidam', 'lga_code' => 'YO06', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 750, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Gujba', 'lga_code' => 'YO07', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 751, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Gulani', 'lga_code' => 'YO08', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 752, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Jakusko', 'lga_code' => 'YO09', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 753, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Karasuwa', 'lga_code' => 'YO10', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 754, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Machina', 'lga_code' => 'YO11', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 755, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Nangere', 'lga_code' => 'YO12', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 756, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Nguru', 'lga_code' => 'YO13', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 757, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Potiskum', 'lga_code' => 'YO14', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 758, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Tarmuwa', 'lga_code' => 'YO15', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 759, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Yunusari', 'lga_code' => 'YO16', 'zone' => 'north_east', 'is_capital' => 0],
            ['id' => 760, 'state_name' => 'Yobe', 'state_code' => 'YO', 'lga_name' => 'Yusufari', 'lga_code' => 'YO17', 'zone' => 'north_east', 'is_capital' => 0],

            // Zamfara State (14 LGAs)
            ['id' => 761, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Anka', 'lga_code' => 'ZA01', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 762, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Bakura', 'lga_code' => 'ZA02', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 763, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Birnin Magaji/Kiyaw', 'lga_code' => 'ZA03', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 764, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Bukkuyum', 'lga_code' => 'ZA04', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 765, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Bungudu', 'lga_code' => 'ZA05', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 766, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Gummi', 'lga_code' => 'ZA06', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 767, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Gusau', 'lga_code' => 'ZA07', 'zone' => 'north_west', 'is_capital' => 1],
            ['id' => 768, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Kaura Namoda', 'lga_code' => 'ZA08', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 769, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Maradun', 'lga_code' => 'ZA09', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 770, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Maru', 'lga_code' => 'ZA10', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 771, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Shinkafi', 'lga_code' => 'ZA11', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 772, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Talata Mafara', 'lga_code' => 'ZA12', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 773, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Tsafe', 'lga_code' => 'ZA13', 'zone' => 'north_west', 'is_capital' => 0],
            ['id' => 774, 'state_name' => 'Zamfara', 'state_code' => 'ZA', 'lga_name' => 'Zurmi', 'lga_code' => 'ZA14', 'zone' => 'north_west', 'is_capital' => 0],
        ];

        // Insert all data
        foreach ($data as &$row) {
            $row['is_active'] = 1;
            $row['created_at'] = now();
            $row['updated_at'] = now();
        }

        DB::table('states_lgas')->insert($data);

        $this->command->info('✅ Inserted 13 states with 298 LGAs: Adamawa, Bauchi, Borno, Gombe, Jigawa, Kaduna, Kano, Katsina, Kebbi, Sokoto, Taraba, Yobe, Zamfara');
    }
}
