<?php

namespace App\Constants;

/**
 * Auto-generated database field constants
 * Generated on: 2025-10-06 17:24:54
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run 'php artisan generate:db-constants' to regenerate
 */
class DatabaseFields
{
    // ============================================
    // TABLE FIELD CONSTANTS
    // ============================================

    /**
     * ATTENDANCE_RECORDS table fields
     */
    const ATTENDANCE_RECORDS = [
        'ID' => 'id',
        'ATTENDANCE_UPLOAD_ID' => 'attendance_upload_id',
        'CLIENT_ID' => 'client_id',
        'STAFF_ID' => 'staff_id',
        'EMPLOYEE_ID' => 'employee_id',
        'EMPLOYEE_CODE' => 'employee_code',
        'PAY_GRADE_STRUCTURE_ID' => 'pay_grade_structure_id',
        'DIRECT_ID_MATCHED' => 'direct_id_matched',
        'VALIDATION_ERRORS' => 'validation_errors',
        'RECORD_STATUS' => 'record_status',
        'TEMPLATE_AVAILABLE' => 'template_available',
        'TEMPLATE_NAME' => 'template_name',
        'READY_FOR_CALCULATION' => 'ready_for_calculation',
        'EMPLOYEE_NAME' => 'employee_name',
        'DESIGNATION' => 'designation',
        'PAYROLL_MONTH' => 'payroll_month',
        'DAYS_WORKED' => 'days_worked',
        'CALCULATION_DETAILS' => 'calculation_details',
        'STATUS' => 'status',
        'ATTENDANCE_FACTOR' => 'attendance_factor',
        'TOTAL_EXPECTED_DAYS' => 'total_expected_days',
        'ACTUAL_WORKING_DAYS' => 'actual_working_days',
        'PRORATED_PERCENTAGE' => 'prorated_percentage',
        'CALCULATION_METHOD' => 'calculation_method',
        'CALCULATION_METADATA' => 'calculation_metadata',
        'CALCULATED_AT' => 'calculated_at',
        'CALCULATED_BY' => 'calculated_by',
        'PROCESSING_NOTES' => 'processing_notes',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * ATTENDANCE_UPLOADS table fields
     */
    const ATTENDANCE_UPLOADS = [
        'ID' => 'id',
        'CLIENT_ID' => 'client_id',
        'FILE_NAME' => 'file_name',
        'FILE_PATH' => 'file_path',
        'FILE_TYPE' => 'file_type',
        'TOTAL_RECORDS' => 'total_records',
        'PROCESSED_RECORDS' => 'processed_records',
        'FAILED_RECORDS' => 'failed_records',
        'PROCESSING_STATUS' => 'processing_status',
        'PROCESSING_ERRORS' => 'processing_errors',
        'FORMAT_VALIDATION_RESULTS' => 'format_validation_results',
        'MATCHING_VALIDATION_RESULTS' => 'matching_validation_results',
        'TEMPLATE_COVERAGE_RESULTS' => 'template_coverage_results',
        'SUCCESSFULLY_MATCHED' => 'successfully_matched',
        'FAILED_MATCHES' => 'failed_matches',
        'MATCH_PERCENTAGE' => 'match_percentage',
        'VALIDATION_STATUS' => 'validation_status',
        'READY_FOR_PROCESSING' => 'ready_for_processing',
        'VALIDATION_COMPLETED_AT' => 'validation_completed_at',
        'PAYROLL_MONTH' => 'payroll_month',
        'UPLOADED_BY' => 'uploaded_by',
        'PROCESSED_AT' => 'processed_at',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * AUDIT_LOGS table fields
     */
    const AUDIT_LOGS = [
        'ID' => 'id',
        'USER_ID' => 'user_id',
        'USER_NAME' => 'user_name',
        'ACTION' => 'action',
        'TABLE_NAME' => 'table_name',
        'RECORD_ID' => 'record_id',
        'OLD_VALUES' => 'old_values',
        'NEW_VALUES' => 'new_values',
        'DESCRIPTION' => 'description',
        'IP_ADDRESS' => 'ip_address',
        'USER_AGENT' => 'user_agent',
        'MODULE' => 'module',
        'CREATED_AT' => 'created_at',
    ];

    /**
     * BOARDING_REQUESTS table fields
     */
    const BOARDING_REQUESTS = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'CLIENT_ID' => 'client_id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'JOB_STRUCTURE_ID' => 'job_structure_id',
        'PAY_GRADE_STRUCTURE_ID' => 'pay_grade_structure_id',
        'OFFER_LETTER_TEMPLATE_ID' => 'offer_letter_template_id',
        'STATUS' => 'status',
        'PROPOSED_START_DATE' => 'proposed_start_date',
        'CANDIDATE_FILLED_FIELDS' => 'candidate_filled_fields',
        'REJECTION_REASON' => 'rejection_reason',
        'OFFER_SENT_AT' => 'offer_sent_at',
        'OFFER_RESPONDED_AT' => 'offer_responded_at',
        'ONBOARDED_AT' => 'onboarded_at',
        'CREATED_BY' => 'created_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * BOARDING_TIMELINE table fields
     */
    const BOARDING_TIMELINE = [
        'ID' => 'id',
        'BOARDING_REQUEST_ID' => 'boarding_request_id',
        'ACTION' => 'action',
        'DESCRIPTION' => 'description',
        'DETAILS' => 'details',
        'PERFORMED_BY' => 'performed_by',
        'PERFORMED_AT' => 'performed_at',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CANDIDATE_DOCUMENTS table fields
     */
    const CANDIDATE_DOCUMENTS = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'DOCUMENT_TYPE' => 'document_type',
        'FILE_PATH' => 'file_path',
        'ORIGINAL_NAME' => 'original_name',
        'FILE_SIZE' => 'file_size',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CANDIDATE_EDUCATION table fields
     */
    const CANDIDATE_EDUCATION = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'INSTITUTION_NAME' => 'institution_name',
        'QUALIFICATION_TYPE' => 'qualification_type',
        'FIELD_OF_STUDY' => 'field_of_study',
        'GRADE_RESULT' => 'grade_result',
        'START_YEAR' => 'start_year',
        'END_YEAR' => 'end_year',
        'IS_CURRENT' => 'is_current',
        'CERTIFICATE_FILE' => 'certificate_file',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CANDIDATE_EMERGENCY_CONTACTS table fields
     */
    const CANDIDATE_EMERGENCY_CONTACTS = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'CONTACT_TYPE' => 'contact_type',
        'FULL_NAME' => 'full_name',
        'RELATIONSHIP' => 'relationship',
        'PHONE_PRIMARY' => 'phone_primary',
        'PHONE_SECONDARY' => 'phone_secondary',
        'EMAIL' => 'email',
        'ADDRESS' => 'address',
        'IS_PRIMARY' => 'is_primary',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
        'EMERGENCY_STATE_OF_RESIDENCE' => 'emergency_state_of_residence',
        'EMERGENCY_LOCAL_GOVERNMENT_RESIDENCE' => 'emergency_local_government_residence',
        'EMERGENCY_ADDRESS' => 'emergency_address',
        'EMERGENCY_ADDRESS_LINE_2' => 'emergency_address_line_2',
    ];

    /**
     * CANDIDATE_EXPERIENCE table fields
     */
    const CANDIDATE_EXPERIENCE = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'COMPANY_NAME' => 'company_name',
        'POSITION' => 'position',
        'JOB_DESCRIPTION' => 'job_description',
        'START_DATE' => 'start_date',
        'END_DATE' => 'end_date',
        'IS_CURRENT' => 'is_current',
        'REASON_FOR_LEAVING' => 'reason_for_leaving',
        'LAST_SALARY' => 'last_salary',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CANDIDATE_JOB_APPLICATIONS table fields
     */
    const CANDIDATE_JOB_APPLICATIONS = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'APPLICATION_STATUS' => 'application_status',
        'COVER_LETTER' => 'cover_letter',
        'SALARY_EXPECTATIONS' => 'salary_expectations',
        'MOTIVATION' => 'motivation',
        'AVAILABILITY' => 'availability',
        'MEETS_LOCATION_CRITERIA' => 'meets_location_criteria',
        'MEETS_AGE_CRITERIA' => 'meets_age_criteria',
        'MEETS_EXPERIENCE_CRITERIA' => 'meets_experience_criteria',
        'ELIGIBILITY_SCORE' => 'eligibility_score',
        'APPLIED_AT' => 'applied_at',
        'LAST_STATUS_CHANGE' => 'last_status_change',
        'STATUS_HISTORY' => 'status_history',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
        'IS_ELIGIBLE' => 'is_eligible',
    ];

    /**
     * CANDIDATE_PRIMARY_EDUCATION table fields
     */
    const CANDIDATE_PRIMARY_EDUCATION = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'PRIMARY_YEAR' => 'primary_year',
        'SECONDARY_YEAR' => 'secondary_year',
        'HIGHEST_LEVEL' => 'highest_level',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CANDIDATE_PROFILES table fields
     */
    const CANDIDATE_PROFILES = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'MIDDLE_NAME' => 'middle_name',
        'FORMAL_NAME' => 'formal_name',
        'GENDER' => 'gender',
        'MARITAL_STATUS' => 'marital_status',
        'NATIONALITY' => 'nationality',
        'STATE_LGA_ID' => 'state_lga_id',
        'CURRENT_ADDRESS_STATE_LGA_ID' => 'current_address_state_lga_id',
        'STATE_OF_ORIGIN' => 'state_of_origin',
        'LOCAL_GOVERNMENT' => 'local_government',
        'NATIONAL_ID_NO' => 'national_id_no',
        'PHONE_PRIMARY' => 'phone_primary',
        'PHONE_SECONDARY' => 'phone_secondary',
        'ADDRESS_CURRENT' => 'address_current',
        'ADDRESS_LINE_2_CURRENT' => 'address_line_2_current',
        'STATE_OF_RESIDENCE_PERMANENT' => 'state_of_residence_permanent',
        'LOCAL_GOVERNMENT_RESIDENCE_PERMANENT' => 'local_government_residence_permanent',
        'ADDRESS_PERMANENT' => 'address_permanent',
        'ADDRESS_LINE_2_PERMANENT' => 'address_line_2_permanent',
        'PROFILE_PICTURE' => 'profile_picture',
        'BLOOD_GROUP' => 'blood_group',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
        'STATE_OF_RESIDENCE' => 'state_of_residence',
        'LOCAL_GOVERNMENT_RESIDENCE' => 'local_government_residence',
        'STATE_OF_RESIDENCE_CURRENT' => 'state_of_residence_current',
        'LOCAL_GOVERNMENT_RESIDENCE_CURRENT' => 'local_government_residence_current',
    ];

    /**
     * CANDIDATE_SECONDARY_EDUCATION table fields
     */
    const CANDIDATE_SECONDARY_EDUCATION = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'SCHOOL_NAME' => 'school_name',
        'START_YEAR' => 'start_year',
        'END_YEAR' => 'end_year',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CANDIDATE_TERTIARY_EDUCATION table fields
     */
    const CANDIDATE_TERTIARY_EDUCATION = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'INSTITUTE_NAME' => 'institute_name',
        'QUALIFICATION_TYPE' => 'qualification_type',
        'FIELD_OF_STUDY' => 'field_of_study',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CANDIDATES table fields
     */
    const CANDIDATES = [
        'ID' => 'id',
        'EMAIL' => 'email',
        'FIRST_NAME' => 'first_name',
        'LAST_NAME' => 'last_name',
        'PHONE' => 'phone',
        'DATE_OF_BIRTH' => 'date_of_birth',
        'EMAIL_VERIFIED_AT' => 'email_verified_at',
        'PASSWORD' => 'password',
        'PROFILE_COMPLETED' => 'profile_completed',
        'STATUS' => 'status',
        'REMEMBER_TOKEN' => 'remember_token',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CLIENT_CONTRACTS table fields
     */
    const CLIENT_CONTRACTS = [
        'ID' => 'id',
        'CONTRACT_CODE' => 'contract_code',
        'CLIENT_ID' => 'client_id',
        'SERVICE_TYPE' => 'service_type',
        'CONTRACT_START_DATE' => 'contract_start_date',
        'CONTRACT_END_DATE' => 'contract_end_date',
        'STATUS' => 'status',
        'NOTES' => 'notes',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CLIENT_INTERVIEW_FEEDBACK table fields
     */
    const CLIENT_INTERVIEW_FEEDBACK = [
        'ID' => 'id',
        'CLIENT_INTERVIEW_ID' => 'client_interview_id',
        'CANDIDATE_ID' => 'candidate_id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'FEEDBACK_STATUS' => 'feedback_status',
        'COMMENTS' => 'comments',
        'CREATED_BY' => 'created_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CLIENT_INTERVIEWS table fields
     */
    const CLIENT_INTERVIEWS = [
        'ID' => 'id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'CANDIDATE_ID' => 'candidate_id',
        'CLIENT_ID' => 'client_id',
        'INTERVIEW_TYPE' => 'interview_type',
        'INTERVIEW_DATE' => 'interview_date',
        'INTERVIEW_TIME' => 'interview_time',
        'CONTACT_PERSON' => 'contact_person',
        'CONTACT_PERSON_PHONE' => 'contact_person_phone',
        'MEETING_LINK' => 'meeting_link',
        'LOCATION' => 'location',
        'STATUS' => 'status',
        'NOTES' => 'notes',
        'CREATED_BY' => 'created_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CLIENT_STAFF_TYPES table fields
     */
    const CLIENT_STAFF_TYPES = [
        'ID' => 'id',
        'CLIENT_ID' => 'client_id',
        'TYPE_CODE' => 'type_code',
        'TITLE' => 'title',
        'DESCRIPTION' => 'description',
        'SALARY_STRUCTURE' => 'salary_structure',
        'BENEFITS' => 'benefits',
        'DEDUCTIONS' => 'deductions',
        'GRADE_LEVEL' => 'grade_level',
        'IS_ACTIVE' => 'is_active',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CLIENTS table fields
     */
    const CLIENTS = [
        'ID' => 'id',
        'ORGANISATION_NAME' => 'organisation_name',
        'CAC_REGISTRATION_NUMBER' => 'cac_registration_number',
        'SLUG' => 'slug',
        'PREFIX' => 'prefix',
        'HEAD_OFFICE_ADDRESS' => 'head_office_address',
        'PHONE' => 'phone',
        'INDUSTRY_CATEGORY' => 'industry_category',
        'CLIENT_CATEGORY' => 'client_category',
        'PAY_CALCULATION_BASIS' => 'pay_calculation_basis',
        'STATUS' => 'status',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * CONTRACT_PARTICULARS_MASTER table fields
     */
    const CONTRACT_PARTICULARS_MASTER = [
        'ID' => 'id',
        'CATEGORY' => 'category',
        'NAME' => 'name',
        'CODE' => 'code',
        'DEFAULT_ENABLED' => 'default_enabled',
        'DISPLAY_ORDER' => 'display_order',
        'IS_ACTIVE' => 'is_active',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * EMOLUMENT_COMPONENTS table fields
     */
    const EMOLUMENT_COMPONENTS = [
        'ID' => 'id',
        'COMPONENT_CODE' => 'component_code',
        'COMPONENT_NAME' => 'component_name',
        'STATUS' => 'status',
        'TYPE' => 'type',
        'CLASS' => 'class',
        'CLIENT_ACCOUNT' => 'client_account',
        'LEDGER_ACCOUNT_CODE' => 'ledger_account_code',
        'LEDGER_ACCOUNT_NAME' => 'ledger_account_name',
        'CATEGORY' => 'category',
        'IS_TAXABLE' => 'is_taxable',
        'CALCULATION_METHOD' => 'calculation_method',
        'DESCRIPTION' => 'description',
        'DISPLAY_ORDER' => 'display_order',
        'IS_ACTIVE' => 'is_active',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * GENERATED_INVOICES table fields
     */
    const GENERATED_INVOICES = [
        'ID' => 'id',
        'INVOICE_NUMBER' => 'invoice_number',
        'CLIENT_ID' => 'client_id',
        'ATTENDANCE_UPLOAD_ID' => 'attendance_upload_id',
        'INVOICE_MONTH' => 'invoice_month',
        'INVOICE_TYPE' => 'invoice_type',
        'TOTAL_EMPLOYEES' => 'total_employees',
        'GROSS_PAYROLL' => 'gross_payroll',
        'TOTAL_DEDUCTIONS' => 'total_deductions',
        'NET_PAYROLL' => 'net_payroll',
        'MANAGEMENT_FEE' => 'management_fee',
        'VAT_AMOUNT' => 'vat_amount',
        'WHT_AMOUNT' => 'wht_amount',
        'TOTAL_INVOICE_AMOUNT' => 'total_invoice_amount',
        'STATUS' => 'status',
        'EXCEL_FILE_PATH' => 'excel_file_path',
        'CALCULATION_BREAKDOWN' => 'calculation_breakdown',
        'GENERATED_BY' => 'generated_by',
        'GENERATED_AT' => 'generated_at',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * INTERVIEW_INVITATIONS table fields
     */
    const INTERVIEW_INVITATIONS = [
        'ID' => 'id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'CANDIDATE_ID' => 'candidate_id',
        'INVITATION_TYPE' => 'invitation_type',
        'MESSAGE' => 'message',
        'INTERVIEW_DATE' => 'interview_date',
        'INTERVIEW_TIME' => 'interview_time',
        'LOCATION' => 'location',
        'INTERVIEW_TYPE' => 'interview_type',
        'STATUS' => 'status',
        'SENT_AT' => 'sent_at',
        'RESPONDED_AT' => 'responded_at',
        'CANDIDATE_RESPONSE' => 'candidate_response',
        'SENT_BY' => 'sent_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * INTERVIEW_SCHEDULES table fields
     */
    const INTERVIEW_SCHEDULES = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'INTERVIEW_TYPE' => 'interview_type',
        'INTERVIEW_MODE' => 'interview_mode',
        'SCHEDULED_AT' => 'scheduled_at',
        'DURATION_MINUTES' => 'duration_minutes',
        'MEETING_LINK' => 'meeting_link',
        'LOCATION' => 'location',
        'INSTRUCTIONS' => 'instructions',
        'STATUS' => 'status',
        'INTERVIEWER_NOTES' => 'interviewer_notes',
        'OUTCOME' => 'outcome',
        'RATING' => 'rating',
        'FEEDBACK' => 'feedback',
        'SCHEDULED_BY' => 'scheduled_by',
        'COMPLETED_AT' => 'completed_at',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * INVOICE_LINE_ITEMS table fields
     */
    const INVOICE_LINE_ITEMS = [
        'ID' => 'id',
        'GENERATED_INVOICE_ID' => 'generated_invoice_id',
        'ATTENDANCE_RECORD_ID' => 'attendance_record_id',
        'EMPLOYEE_ID' => 'employee_id',
        'EMPLOYEE_NAME' => 'employee_name',
        'DESIGNATION' => 'designation',
        'DAYS_WORKED' => 'days_worked',
        'BASIC_SALARY' => 'basic_salary',
        'GROSS_PAY' => 'gross_pay',
        'PAYE_DEDUCTION' => 'paye_deduction',
        'NHF_DEDUCTION' => 'nhf_deduction',
        'NSITF_DEDUCTION' => 'nsitf_deduction',
        'OTHER_DEDUCTIONS' => 'other_deductions',
        'TOTAL_DEDUCTIONS' => 'total_deductions',
        'NET_PAY' => 'net_pay',
        'ALLOWANCES_BREAKDOWN' => 'allowances_breakdown',
        'DEDUCTIONS_BREAKDOWN' => 'deductions_breakdown',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * INVOICE_TEMPLATES table fields
     */
    const INVOICE_TEMPLATES = [
        'ID' => 'id',
        'CLIENT_ID' => 'client_id',
        'PAY_GRADE_STRUCTURE_ID' => 'pay_grade_structure_id',
        'TEMPLATE_NAME' => 'template_name',
        'DESCRIPTION' => 'description',
        'CUSTOM_COMPONENTS' => 'custom_components',
        'STATUTORY_COMPONENTS' => 'statutory_components',
        'CALCULATION_RULES' => 'calculation_rules',
        'ANNUAL_DIVISION_FACTOR' => 'annual_division_factor',
        'TEMPLATE_VERSION' => 'template_version',
        'USE_CREDIT_TO_BANK_MODEL' => 'use_credit_to_bank_model',
        'SERVICE_FEE_PERCENTAGE' => 'service_fee_percentage',
        'ATTENDANCE_CALCULATION_METHOD' => 'attendance_calculation_method',
        'PRORATE_SALARY' => 'prorate_salary',
        'MINIMUM_ATTENDANCE_FACTOR' => 'minimum_attendance_factor',
        'IS_ACTIVE' => 'is_active',
        'IS_DEFAULT' => 'is_default',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'LAST_USED_AT' => 'last_used_at',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * JOB_CATEGORIES table fields
     */
    const JOB_CATEGORIES = [
        'ID' => 'id',
        'NAME' => 'name',
        'SLUG' => 'slug',
        'DESCRIPTION' => 'description',
        'IS_ACTIVE' => 'is_active',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * JOB_INTERVIEWS table fields
     */
    const JOB_INTERVIEWS = [
        'ID' => 'id',
        'JOB_APPLICATION_ID' => 'job_application_id',
        'INTERVIEWER_ID' => 'interviewer_id',
        'INTERVIEW_DATE' => 'interview_date',
        'INTERVIEW_TIME' => 'interview_time',
        'LOCATION' => 'location',
        'INTERVIEW_TYPE' => 'interview_type',
        'STATUS' => 'status',
        'NOTES' => 'notes',
        'FEEDBACK' => 'feedback',
        'RATING' => 'rating',
        'RECOMMENDATION' => 'recommendation',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * JOB_STRUCTURES table fields
     */
    const JOB_STRUCTURES = [
        'ID' => 'id',
        'CLIENT_ID' => 'client_id',
        'JOB_CODE' => 'job_code',
        'JOB_TITLE' => 'job_title',
        'DESCRIPTION' => 'description',
        'CONTRACT_TYPE' => 'contract_type',
        'CONTRACT_NATURE' => 'contract_nature',
        'PAY_STRUCTURES' => 'pay_structures',
        'IS_ACTIVE' => 'is_active',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * LEAVE_APPLICATIONS table fields
     */
    const LEAVE_APPLICATIONS = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'LEAVE_TYPE_ID' => 'leave_type_id',
        'START_DATE' => 'start_date',
        'END_DATE' => 'end_date',
        'DAYS' => 'days',
        'REASON' => 'reason',
        'STATUS' => 'status',
        'APPROVER_ID' => 'approver_id',
        'COMMENTS' => 'comments',
        'APPLIED_AT' => 'applied_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * LEAVE_TYPES table fields
     */
    const LEAVE_TYPES = [
        'ID' => 'id',
        'NAME' => 'name',
        'ANNUAL_ALLOWANCE' => 'annual_allowance',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * OFFER_LETTER_TEMPLATES table fields
     */
    const OFFER_LETTER_TEMPLATES = [
        'ID' => 'id',
        'NAME' => 'name',
        'CLIENT_ID' => 'client_id',
        'JOB_STRUCTURE_ID' => 'job_structure_id',
        'PAY_GRADE_STRUCTURE_ID' => 'pay_grade_structure_id',
        'HEADER_CONFIG' => 'header_config',
        'CONTENT' => 'content',
        'SECTIONS' => 'sections',
        'FOOTER_CONFIG' => 'footer_config',
        'VARIABLES' => 'variables',
        'STATUS' => 'status',
        'DESCRIPTION' => 'description',
        'SMART_ELEMENTS' => 'smart_elements',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * OFFER_RESPONSES table fields
     */
    const OFFER_RESPONSES = [
        'ID' => 'id',
        'BOARDING_REQUEST_ID' => 'boarding_request_id',
        'CANDIDATE_ID' => 'candidate_id',
        'RESPONSE_TYPE' => 'response_type',
        'CANDIDATE_MESSAGE' => 'candidate_message',
        'PREFERRED_START_DATE' => 'preferred_start_date',
        'UPDATED_CANDIDATE_INFO' => 'updated_candidate_info',
        'RESPONDED_AT' => 'responded_at',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * PAY_GRADE_STRUCTURES table fields
     */
    const PAY_GRADE_STRUCTURES = [
        'ID' => 'id',
        'JOB_STRUCTURE_ID' => 'job_structure_id',
        'GRADE_NAME' => 'grade_name',
        'GRADE_CODE' => 'grade_code',
        'PAY_STRUCTURE_TYPE' => 'pay_structure_type',
        'EMOLUMENTS' => 'emoluments',
        'TOTAL_COMPENSATION' => 'total_compensation',
        'CURRENCY' => 'currency',
        'IS_ACTIVE' => 'is_active',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
        'BASIC_SALARY' => 'basic_salary',
        'TRANSPORT_ALLOWANCE' => 'transport_allowance',
        'HOUSING_ALLOWANCE' => 'housing_allowance',
        'MEAL_ALLOWANCE' => 'meal_allowance',
    ];

    /**
     * PAY_STRUCTURE_TYPES table fields
     */
    const PAY_STRUCTURE_TYPES = [
        'ID' => 'id',
        'TYPE_CODE' => 'type_code',
        'TYPE_NAME' => 'type_name',
        'CONTRACT_TYPE' => 'contract_type',
        'CONTRACT_NATURE' => 'contract_nature',
        'PRIMARY_COMPONENT' => 'primary_component',
        'SECONDARY_COMPONENT' => 'secondary_component',
        'DESCRIPTION' => 'description',
        'IS_ACTIVE' => 'is_active',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * PERMISSIONS table fields
     */
    const PERMISSIONS = [
        'ID' => 'id',
        'NAME' => 'name',
        'DISPLAY_NAME' => 'display_name',
        'DESCRIPTION' => 'description',
        'MODULE' => 'module',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * RECRUITMENT_APPLICATIONS_BACKUP table fields
     */
    const RECRUITMENT_APPLICATIONS_BACKUP = [
        'ID' => 'id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'CANDIDATE_ID' => 'candidate_id',
        'COVER_LETTER' => 'cover_letter',
        'EXPECTED_SALARY' => 'expected_salary',
        'AVAILABLE_START_DATE' => 'available_start_date',
        'STATUS' => 'status',
        'NOTES' => 'notes',
        'REVIEWED_BY' => 'reviewed_by',
        'REVIEWED_AT' => 'reviewed_at',
        'APPLICATION_SOURCE' => 'application_source',
        'APPLIED_AT' => 'applied_at',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * RECRUITMENT_REQUESTS table fields
     */
    const RECRUITMENT_REQUESTS = [
        'ID' => 'id',
        'TICKET_ID' => 'ticket_id',
        'STATUS' => 'status',
        'CLIENT_ID' => 'client_id',
        'JOB_STRUCTURE_ID' => 'job_structure_id',
        'GENDER_REQUIREMENT' => 'gender_requirement',
        'RELIGION_REQUIREMENT' => 'religion_requirement',
        'AGE_LIMIT_MIN' => 'age_limit_min',
        'AGE_LIMIT_MAX' => 'age_limit_max',
        'EXPERIENCE_REQUIREMENT' => 'experience_requirement',
        'QUALIFICATIONS' => 'qualifications',
        'SERVICE_LOCATION_ID' => 'service_location_id',
        'LGA' => 'lga',
        'ZONE' => 'zone',
        'SOL_OFFICE_ID' => 'sol_office_id',
        'NUMBER_OF_VACANCIES' => 'number_of_vacancies',
        'COMPENSATION' => 'compensation',
        'SOL_SERVICE_TYPE' => 'sol_service_type',
        'RECRUITMENT_PERIOD_START' => 'recruitment_period_start',
        'RECRUITMENT_PERIOD_END' => 'recruitment_period_end',
        'DESCRIPTION' => 'description',
        'SPECIAL_REQUIREMENTS' => 'special_requirements',
        'PRIORITY_LEVEL' => 'priority_level',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'APPROVED_BY' => 'approved_by',
        'APPROVED_AT' => 'approved_at',
        'CLOSED_AT' => 'closed_at',
        'CLOSED_REASON' => 'closed_reason',
        'REOPEN_REASON' => 'reopen_reason',
        'REOPENED_AT' => 'reopened_at',
        'CLOSURE_REASON' => 'closure_reason',
        'CLOSURE_COMMENTS' => 'closure_comments',
        'STAFF_ACCEPTED_OFFER' => 'staff_accepted_offer',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
        'CLOSED_BY' => 'closed_by',
        'REOPENED_BY' => 'reopened_by',
    ];

    /**
     * ROLE_PERMISSIONS table fields
     */
    const ROLE_PERMISSIONS = [
        'ID' => 'id',
        'ROLE_ID' => 'role_id',
        'PERMISSION_ID' => 'permission_id',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * ROLES table fields
     */
    const ROLES = [
        'ID' => 'id',
        'NAME' => 'name',
        'SLUG' => 'slug',
        'DESCRIPTION' => 'description',
        'PERMISSIONS' => 'permissions',
        'IS_ACTIVE' => 'is_active',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * SERVICE_LOCATIONS table fields
     */
    const SERVICE_LOCATIONS = [
        'ID' => 'id',
        'LOCATION_CODE' => 'location_code',
        'UNIQUE_ID' => 'unique_id',
        'LOCATION_NAME' => 'location_name',
        'SHORT_NAME' => 'short_name',
        'COUNTRY' => 'country',
        'STATE' => 'state',
        'CITY' => 'city',
        'FULL_ADDRESS' => 'full_address',
        'CONTACT_PERSON_NAME' => 'contact_person_name',
        'CONTACT_PERSON_PHONE' => 'contact_person_phone',
        'CONTACT_PERSON_EMAIL' => 'contact_person_email',
        'ADDRESS' => 'address',
        'PIN_CODE' => 'pin_code',
        'PHONE' => 'phone',
        'FAX' => 'fax',
        'NOTES' => 'notes',
        'SOL_REGION' => 'sol_region',
        'SOL_ZONE' => 'sol_zone',
        'CLIENT_ID' => 'client_id',
        'SOL_OFFICE_ID' => 'sol_office_id',
        'IS_ACTIVE' => 'is_active',
        'CREATED_BY' => 'created_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * SERVICE_REQUESTS table fields
     */
    const SERVICE_REQUESTS = [
        'ID' => 'id',
        'CLIENT_ID' => 'client_id',
        'SERVICE_TYPE' => 'service_type',
        'SERVICE_NAME' => 'service_name',
        'SERVICE_CODE' => 'service_code',
        'DESCRIPTION' => 'description',
        'IS_ACTIVE' => 'is_active',
        'CREATED_BY' => 'created_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * SOL_OFFICES table fields
     */
    const SOL_OFFICES = [
        'ID' => 'id',
        'OFFICE_NAME' => 'office_name',
        'OFFICE_CODE' => 'office_code',
        'ZONE' => 'zone',
        'ZONE_NAME' => 'zone_name',
        'STATE_NAME' => 'state_name',
        'STATE_CODE' => 'state_code',
        'CONTROL_TYPE' => 'control_type',
        'CONTROLLED_AREAS' => 'controlled_areas',
        'OFFICE_ADDRESS' => 'office_address',
        'OFFICE_PHONE' => 'office_phone',
        'OFFICE_EMAIL' => 'office_email',
        'MANAGER_NAME' => 'manager_name',
        'IS_ACTIVE' => 'is_active',
        'CREATED_BY' => 'created_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
        'DELETED_AT' => 'deleted_at',
    ];

    /**
     * STAFF table fields
     */
    const STAFF = [
        'ID' => 'id',
        'CANDIDATE_ID' => 'candidate_id',
        'CLIENT_ID' => 'client_id',
        'SERVICE_LOCATION_ID' => 'service_location_id',
        'STAFF_TYPE_ID' => 'staff_type_id',
        'EMPLOYEE_CODE' => 'employee_code',
        'STAFF_ID' => 'staff_id',
        'EMAIL' => 'email',
        'FIRST_NAME' => 'first_name',
        'LAST_NAME' => 'last_name',
        'GENDER' => 'gender',
        'ENTRY_DATE' => 'entry_date',
        'END_DATE' => 'end_date',
        'APPOINTMENT_STATUS' => 'appointment_status',
        'EMPLOYMENT_TYPE' => 'employment_type',
        'STATUS' => 'status',
        'PAY_GRADE_STRUCTURE_ID' => 'pay_grade_structure_id',
        'SALARY_EFFECTIVE_DATE' => 'salary_effective_date',
        'SALARY_CURRENCY' => 'salary_currency',
        'JOB_TITLE' => 'job_title',
        'DEPARTMENT' => 'department',
        'LOCATION' => 'location',
        'STATE_LGA_ID' => 'state_lga_id',
        'SUPERVISOR_ID' => 'supervisor_id',
        'LEAVE_CATEGORY_LEVEL' => 'leave_category_level',
        'APPRAISAL_CATEGORY' => 'appraisal_category',
        'TAX_ID_NO' => 'tax_id_no',
        'PF_NO' => 'pf_no',
        'PF_ADMINISTRATOR' => 'pf_administrator',
        'PFA_CODE' => 'pfa_code',
        'BV_NO' => 'bv_no',
        'NHF_ACCOUNT_NO' => 'nhf_account_no',
        'CLIENT_ASSIGNED_CODE' => 'client_assigned_code',
        'DEPLOYMENT_CODE' => 'deployment_code',
        'ONBOARDING_METHOD' => 'onboarding_method',
        'ONBOARDED_BY' => 'onboarded_by',
        'CUSTOM_FIELDS' => 'custom_fields',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_BANKING table fields
     */
    const STAFF_BANKING = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'PAYMENT_MODE' => 'payment_mode',
        'BANK_NAME' => 'bank_name',
        'ACCOUNT_NUMBER' => 'account_number',
        'WAGES_TYPE' => 'wages_type',
        'WEEKDAY_OT_RATE' => 'weekday_ot_rate',
        'HOLIDAY_OT_RATE' => 'holiday_ot_rate',
        'ENTITLED_TO_OT' => 'entitled_to_ot',
        'PENSION_DEDUCTION' => 'pension_deduction',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_BULK_IMPORT_TEMP table fields
     */
    const STAFF_BULK_IMPORT_TEMP = [
        'ID' => 'id',
        'SN' => 'sn',
        'CLIENT_NAME' => 'client_name',
        'EMP_CODE' => 'emp_code',
        'FIRST_NAME' => 'first_name',
        'MIDDLE_NAME' => 'middle_name',
        'LAST_NAME' => 'last_name',
        'GENDER' => 'gender',
        'MARITAL_STATUS' => 'marital_status',
        'DATE_OF_BIRTH' => 'date_of_birth',
        'NATIONALITY' => 'nationality',
        'STATE_OF_ORIGIN' => 'state_of_origin',
        'LOCAL_GOVERNMENT' => 'local_government',
        'NATIONAL_ID_NO' => 'national_id_no',
        'TAX_ID_NO' => 'tax_id_no',
        'PIN_NO' => 'pin_no',
        'PFA_NAME' => 'pfa_name',
        'BANK_VERIFICATION_NO' => 'bank_verification_no',
        'NHF_ACCOUNT_NO' => 'nhf_account_no',
        'ENTRY_DATE' => 'entry_date',
        'CURRENT_RESIDENTIAL_ADDRESS' => 'current_residential_address',
        'MOBILE_PHONE_NO' => 'mobile_phone_no',
        'EMAIL_ID' => 'email_id',
        'PERMANENT_ADDRESS' => 'permanent_address',
        'NEARBY_LANDMARK' => 'nearby_landmark',
        'STATE' => 'state',
        'COUNTRY' => 'country',
        'EMERGENCY_CONTACT_NAME' => 'emergency_contact_name',
        'EMERGENCY_CONTACT_ADDRESS' => 'emergency_contact_address',
        'EMERGENCY_CONTACT_PHONE' => 'emergency_contact_phone',
        'EMERGENCY_CONTACT_EMAIL' => 'emergency_contact_email',
        'EMERGENCY_CONTACT_RELATIONSHIP' => 'emergency_contact_relationship',
        'CATEGORY' => 'category',
        'GRADE' => 'grade',
        'DESIGNATION' => 'designation',
        'DEPARTMENT' => 'department',
        'SERVICE_PLACE' => 'service_place',
        'SERVICE_LOCATION' => 'service_location',
        'STATE_OF_SERVICE' => 'state_of_service',
        'DATE_OF_JOIN' => 'date_of_join',
        'REPORTING_MANAGER' => 'reporting_manager',
        'OFFICE_EMAIL_ID' => 'office_email_id',
        'OFFICE_PHONE_NO' => 'office_phone_no',
        'SCHOOL_1' => 'school_1',
        'GRADUATION_YEAR_1' => 'graduation_year_1',
        'CERTIFICATE_1' => 'certificate_1',
        'SPECIALIZATION_1' => 'specialization_1',
        'SCORE_CLASS_1' => 'score_class_1',
        'SCHOOL_2' => 'school_2',
        'GRADUATION_YEAR_2' => 'graduation_year_2',
        'CERTIFICATE_2' => 'certificate_2',
        'SPECIALIZATION_2' => 'specialization_2',
        'SCORE_CLASS_2' => 'score_class_2',
        'SCHOOL_3' => 'school_3',
        'GRADUATION_YEAR_3' => 'graduation_year_3',
        'CERTIFICATE_3' => 'certificate_3',
        'SPECIALIZATION_3' => 'specialization_3',
        'SCORE_CLASS_3' => 'score_class_3',
        'EMPLOYER_1' => 'employer_1',
        'DESIGNATION_1' => 'designation_1',
        'START_DATE_1' => 'start_date_1',
        'END_DATE_1' => 'end_date_1',
        'EMPLOYER_2' => 'employer_2',
        'DESIGNATION_2' => 'designation_2',
        'START_DATE_2' => 'start_date_2',
        'END_DATE_2' => 'end_date_2',
        'EMPLOYER_3' => 'employer_3',
        'DESIGNATION_3' => 'designation_3',
        'START_DATE_3' => 'start_date_3',
        'END_DATE_3' => 'end_date_3',
        'PAYMENT_MODE' => 'payment_mode',
        'BANK_NAME' => 'bank_name',
        'ACCOUNT_NO' => 'account_no',
        'WAGES_TYPE' => 'wages_type',
        'WD_OT_RATE' => 'wd_ot_rate',
        'HO_OT_RATE' => 'ho_ot_rate',
        'ENTITLED_TO_OT' => 'entitled_to_ot',
        'PENSION_DEDUCTION' => 'pension_deduction',
        'FATHER_NAME' => 'father_name',
        'FATHER_RELATIONSHIP' => 'father_relationship',
        'FATHER_GENDER' => 'father_gender',
        'FATHER_DOB' => 'father_dob',
        'MOTHER_NAME' => 'mother_name',
        'MOTHER_RELATIONSHIP' => 'mother_relationship',
        'MOTHER_GENDER' => 'mother_gender',
        'MOTHER_DOB' => 'mother_dob',
        'NEXT_OF_KIN' => 'next_of_kin',
        'NEXT_OF_KIN_PHONE' => 'next_of_kin_phone',
        'NEXT_OF_KIN_RELATIONSHIP' => 'next_of_kin_relationship',
        'NEXT_OF_KIN_EMAIL' => 'next_of_kin_email',
        'REFEREE_1_NAME' => 'referee_1_name',
        'REFEREE_1_ADDRESS' => 'referee_1_address',
        'REFEREE_1_PHONE' => 'referee_1_phone',
        'REFEREE_1_EMAIL' => 'referee_1_email',
        'REFEREE_2_NAME' => 'referee_2_name',
        'REFEREE_2_ADDRESS' => 'referee_2_address',
        'REFEREE_2_PHONE' => 'referee_2_phone',
        'REFEREE_2_EMAIL' => 'referee_2_email',
        'GUARANTOR_1_NAME' => 'guarantor_1_name',
        'GUARANTOR_1_ADDRESS' => 'guarantor_1_address',
        'GUARANTOR_1_DOB' => 'guarantor_1_dob',
        'GUARANTOR_1_PHONE' => 'guarantor_1_phone',
        'GUARANTOR_1_EMAIL' => 'guarantor_1_email',
        'GUARANTOR_1_BANK_DETAILS' => 'guarantor_1_bank_details',
        'GUARANTOR_1_EMPLOYER' => 'guarantor_1_employer',
        'GUARANTOR_1_RELATIONSHIP' => 'guarantor_1_relationship',
        'GUARANTOR_2_NAME' => 'guarantor_2_name',
        'GUARANTOR_2_ADDRESS' => 'guarantor_2_address',
        'GUARANTOR_2_DOB' => 'guarantor_2_dob',
        'GUARANTOR_2_PHONE' => 'guarantor_2_phone',
        'GUARANTOR_2_EMAIL' => 'guarantor_2_email',
        'GUARANTOR_2_BANK_DETAILS' => 'guarantor_2_bank_details',
        'GUARANTOR_2_EMPLOYER' => 'guarantor_2_employer',
        'GUARANTOR_2_RELATIONSHIP' => 'guarantor_2_relationship',
        'PROCESSED' => 'processed',
        'PROCESSING_ERRORS' => 'processing_errors',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_EDUCATION table fields
     */
    const STAFF_EDUCATION = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'INSTITUTION_NAME' => 'institution_name',
        'CERTIFICATE_TYPE' => 'certificate_type',
        'SPECIALIZATION' => 'specialization',
        'START_YEAR' => 'start_year',
        'END_YEAR' => 'end_year',
        'GRADUATION_YEAR' => 'graduation_year',
        'SCORE_CLASS' => 'score_class',
        'YEAR_OBTAINED' => 'year_obtained',
        'EDUCATION_ORDER' => 'education_order',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_EMERGENCY_CONTACTS table fields
     */
    const STAFF_EMERGENCY_CONTACTS = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'CONTACT_TYPE' => 'contact_type',
        'NAME' => 'name',
        'RELATIONSHIP' => 'relationship',
        'PHONE_NUMBER' => 'phone_number',
        'EMAIL' => 'email',
        'ADDRESS' => 'address',
        'GENDER' => 'gender',
        'DATE_OF_BIRTH' => 'date_of_birth',
        'IS_PRIMARY' => 'is_primary',
        'CONTACT_ORDER' => 'contact_order',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_EXPERIENCE table fields
     */
    const STAFF_EXPERIENCE = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'EMPLOYER_NAME' => 'employer_name',
        'DESIGNATION' => 'designation',
        'START_DATE' => 'start_date',
        'END_DATE' => 'end_date',
        'JOB_DESCRIPTION' => 'job_description',
        'REASON_FOR_LEAVING' => 'reason_for_leaving',
        'LAST_SALARY' => 'last_salary',
        'EXPERIENCE_ORDER' => 'experience_order',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_GUARANTORS table fields
     */
    const STAFF_GUARANTORS = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'NAME' => 'name',
        'ADDRESS' => 'address',
        'DATE_OF_BIRTH' => 'date_of_birth',
        'PHONE_NUMBER' => 'phone_number',
        'EMAIL' => 'email',
        'BANK_DETAILS' => 'bank_details',
        'EMPLOYER_DETAILS' => 'employer_details',
        'RELATIONSHIP_TO_APPLICANT' => 'relationship_to_applicant',
        'GUARANTOR_ORDER' => 'guarantor_order',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_LEGAL_IDS table fields
     */
    const STAFF_LEGAL_IDS = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'NATIONAL_ID_NO' => 'national_id_no',
        'TAX_ID_NO' => 'tax_id_no',
        'PENSION_PIN' => 'pension_pin',
        'PFA_NAME' => 'pfa_name',
        'BANK_VERIFICATION_NO' => 'bank_verification_no',
        'NHF_ACCOUNT_NO' => 'nhf_account_no',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_PERSONAL_INFO table fields
     */
    const STAFF_PERSONAL_INFO = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'MIDDLE_NAME' => 'middle_name',
        'MARITAL_STATUS' => 'marital_status',
        'NATIONALITY' => 'nationality',
        'STATE_OF_ORIGIN' => 'state_of_origin',
        'LOCAL_GOVERNMENT_OF_ORIGIN' => 'local_government_of_origin',
        'CURRENT_ADDRESS' => 'current_address',
        'PERMANENT_ADDRESS' => 'permanent_address',
        'NEARBY_LANDMARK' => 'nearby_landmark',
        'MOBILE_PHONE' => 'mobile_phone',
        'PERSONAL_EMAIL' => 'personal_email',
        'BLOOD_GROUP' => 'blood_group',
        'STATE_OF_RESIDENCE' => 'state_of_residence',
        'LGA_OF_RESIDENCE' => 'lga_of_residence',
        'COUNTRY' => 'country',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_REFERENCES table fields
     */
    const STAFF_REFERENCES = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'NAME' => 'name',
        'ADDRESS' => 'address',
        'PHONE_NUMBER' => 'phone_number',
        'EMAIL' => 'email',
        'REFERENCE_ORDER' => 'reference_order',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STAFF_ROLES table fields
     */
    const STAFF_ROLES = [
        'ID' => 'id',
        'STAFF_ID' => 'staff_id',
        'ROLE_ID' => 'role_id',
        'ASSIGNED_AT' => 'assigned_at',
        'ASSIGNED_BY' => 'assigned_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * STATES_LGAS table fields
     */
    const STATES_LGAS = [
        'ID' => 'id',
        'STATE_NAME' => 'state_name',
        'STATE_CODE' => 'state_code',
        'LGA_NAME' => 'lga_name',
        'LGA_CODE' => 'lga_code',
        'ZONE' => 'zone',
        'IS_CAPITAL' => 'is_capital',
        'IS_ACTIVE' => 'is_active',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * SYSTEM_PREFERENCES table fields
     */
    const SYSTEM_PREFERENCES = [
        'ID' => 'id',
        'PREFERENCE_KEY' => 'preference_key',
        'PREFERENCE_VALUE' => 'preference_value',
        'DESCRIPTION' => 'description',
        'CATEGORY' => 'category',
        'IS_ACTIVE' => 'is_active',
        'CREATED_BY' => 'created_by',
        'UPDATED_BY' => 'updated_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * TEST_ASSIGNMENTS table fields
     */
    const TEST_ASSIGNMENTS = [
        'ID' => 'id',
        'TEST_ID' => 'test_id',
        'CANDIDATE_ID' => 'candidate_id',
        'RECRUITMENT_REQUEST_ID' => 'recruitment_request_id',
        'STATUS' => 'status',
        'ASSIGNED_AT' => 'assigned_at',
        'STARTED_AT' => 'started_at',
        'COMPLETED_AT' => 'completed_at',
        'EXPIRES_AT' => 'expires_at',
        'INVITATION_MESSAGE' => 'invitation_message',
        'EMAIL_SENT' => 'email_sent',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * TEST_QUESTIONS table fields
     */
    const TEST_QUESTIONS = [
        'ID' => 'id',
        'TEST_ID' => 'test_id',
        'QUESTION' => 'question',
        'TYPE' => 'type',
        'OPTIONS' => 'options',
        'CORRECT_ANSWERS' => 'correct_answers',
        'POINTS' => 'points',
        'ORDER_NUMBER' => 'order_number',
        'REQUIRED' => 'required',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * TEST_RESULTS table fields
     */
    const TEST_RESULTS = [
        'ID' => 'id',
        'TEST_ASSIGNMENT_ID' => 'test_assignment_id',
        'CANDIDATE_ID' => 'candidate_id',
        'TEST_ID' => 'test_id',
        'ANSWERS' => 'answers',
        'TOTAL_QUESTIONS' => 'total_questions',
        'CORRECT_ANSWERS' => 'correct_answers',
        'SCORE_PERCENTAGE' => 'score_percentage',
        'TIME_TAKEN' => 'time_taken',
        'RESULT_STATUS' => 'result_status',
        'STARTED_AT' => 'started_at',
        'COMPLETED_AT' => 'completed_at',
        'QUESTION_RESULTS' => 'question_results',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * TESTS table fields
     */
    const TESTS = [
        'ID' => 'id',
        'TITLE' => 'title',
        'DESCRIPTION' => 'description',
        'INSTRUCTIONS' => 'instructions',
        'TIME_LIMIT' => 'time_limit',
        'PASS_SCORE' => 'pass_score',
        'STATUS' => 'status',
        'RANDOMIZE_QUESTIONS' => 'randomize_questions',
        'SHOW_RESULTS_IMMEDIATELY' => 'show_results_immediately',
        'ALLOW_RETAKE' => 'allow_retake',
        'MAX_ATTEMPTS' => 'max_attempts',
        'CREATED_BY' => 'created_by',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    /**
     * USERS table fields
     */
    const USERS = [
        'ID' => 'id',
        'NAME' => 'name',
        'EMAIL' => 'email',
        'USERNAME' => 'username',
        'EMAIL_VERIFIED_AT' => 'email_verified_at',
        'PASSWORD' => 'password',
        'PREFERENCES' => 'preferences',
        'ROLE' => 'role',
        'USER_TYPE' => 'user_type',
        'PROFILE_ID' => 'profile_id',
        'IS_ACTIVE' => 'is_active',
        'REMEMBER_TOKEN' => 'remember_token',
        'CREATED_AT' => 'created_at',
        'UPDATED_AT' => 'updated_at',
    ];

    // ============================================
    // ENUM VALUE CONSTANTS
    // ============================================

    /**
     * ATTENDANCE_RECORDS_RECORD_STATUS enum values
     */
    const ATTENDANCE_RECORDS_RECORD_STATUS = [
        'VALID' => 'valid',
        'INVALID' => 'invalid',
        'PENDING_REVIEW' => 'pending_review',
    ];

    /**
     * ATTENDANCE_RECORDS_STATUS enum values
     */
    const ATTENDANCE_RECORDS_STATUS = [
        'PENDING' => 'pending',
        'PROCESSED' => 'processed',
        'EXCLUDED' => 'excluded',
    ];

    /**
     * ATTENDANCE_RECORDS_CALCULATION_METHOD enum values
     */
    const ATTENDANCE_RECORDS_CALCULATION_METHOD = [
        'WORKING_DAYS' => 'working_days',
        'CALENDAR_DAYS' => 'calendar_days',
    ];

    /**
     * ATTENDANCE_UPLOADS_PROCESSING_STATUS enum values
     */
    const ATTENDANCE_UPLOADS_PROCESSING_STATUS = [
        'PENDING' => 'pending',
        'PROCESSING' => 'processing',
        'COMPLETED' => 'completed',
        'FAILED' => 'failed',
    ];

    /**
     * ATTENDANCE_UPLOADS_VALIDATION_STATUS enum values
     */
    const ATTENDANCE_UPLOADS_VALIDATION_STATUS = [
        'PENDING' => 'pending',
        'VALIDATED' => 'validated',
        'PARTIAL' => 'partial',
        'FAILED' => 'failed',
    ];

    /**
     * BOARDING_REQUESTS_STATUS enum values
     */
    const BOARDING_REQUESTS_STATUS = [
        'PENDING' => 'pending',
        'OFFER_SENT' => 'offer_sent',
        'OFFER_ACCEPTED' => 'offer_accepted',
        'OFFER_REJECTED' => 'offer_rejected',
        'ONBOARDED' => 'onboarded',
        'CANCELLED' => 'cancelled',
    ];

    /**
     * BOARDING_TIMELINE_ACTION enum values
     */
    const BOARDING_TIMELINE_ACTION = [
        'REQUEST_CREATED' => 'request_created',
        'OFFER_SENT' => 'offer_sent',
        'OFFER_VIEWED' => 'offer_viewed',
        'OFFER_ACCEPTED' => 'offer_accepted',
        'OFFER_REJECTED' => 'offer_rejected',
        'CANDIDATE_INFO_UPDATED' => 'candidate_info_updated',
        'ONBOARDING_STARTED' => 'onboarding_started',
        'ONBOARDING_COMPLETED' => 'onboarding_completed',
        'STATUS_CHANGED' => 'status_changed',
    ];

    /**
     * CANDIDATE_DOCUMENTS_DOCUMENT_TYPE enum values
     */
    const CANDIDATE_DOCUMENTS_DOCUMENT_TYPE = [
        'CV' => 'cv',
        'CERTIFICATE' => 'certificate',
        'ID_CARD' => 'id_card',
        'PASSPORT' => 'passport',
    ];

    /**
     * CANDIDATE_JOB_APPLICATIONS_APPLICATION_STATUS enum values
     */
    const CANDIDATE_JOB_APPLICATIONS_APPLICATION_STATUS = [
        'APPLIED' => 'applied',
        'UNDER_REVIEW' => 'under_review',
        'TEST_SENT' => 'test_sent',
        'TEST_COMPLETED' => 'test_completed',
        'INTERVIEW_SCHEDULED' => 'interview_scheduled',
        'INTERVIEW_COMPLETED' => 'interview_completed',
        'ACCEPTED' => 'accepted',
        'REJECTED' => 'rejected',
    ];

    /**
     * CANDIDATE_PROFILES_GENDER enum values
     */
    const CANDIDATE_PROFILES_GENDER = [
        'MALE' => 'male',
        'FEMALE' => 'female',
    ];

    /**
     * CANDIDATE_PROFILES_MARITAL_STATUS enum values
     */
    const CANDIDATE_PROFILES_MARITAL_STATUS = [
        'SINGLE' => 'single',
        'MARRIED' => 'married',
        'DIVORCED' => 'divorced',
        'WIDOWED' => 'widowed',
    ];

    /**
     * CANDIDATE_PROFILES_BLOOD_GROUP enum values
     */
    const CANDIDATE_PROFILES_BLOOD_GROUP = [
        'A+' => 'A+',
        'A_' => 'A-',
        'B+' => 'B+',
        'B_' => 'B-',
        'AB+' => 'AB+',
        'AB_' => 'AB-',
        'O+' => 'O+',
        'O_' => 'O-',
    ];

    /**
     * CANDIDATES_STATUS enum values
     */
    const CANDIDATES_STATUS = [
        'PENDING' => 'pending',
        'ACTIVE' => 'active',
        'INACTIVE' => 'inactive',
    ];

    /**
     * CLIENT_CONTRACTS_SERVICE_TYPE enum values
     */
    const CLIENT_CONTRACTS_SERVICE_TYPE = [
        'RECRUITMENT_SERVICE' => 'Recruitment Service',
        'TEMPORARY_STAFF_SERVICE' => 'Temporary Staff Service',
        'MANAGED_STAFF_SERVICE' => 'Managed Staff Service',
        'PAYROLL_SERVICES' => 'Payroll Services',
    ];

    /**
     * CLIENT_CONTRACTS_STATUS enum values
     */
    const CLIENT_CONTRACTS_STATUS = [
        'ACTIVE' => 'active',
        'INACTIVE' => 'inactive',
        'EXPIRED' => 'expired',
        'TERMINATED' => 'terminated',
    ];

    /**
     * CLIENT_INTERVIEW_FEEDBACK_FEEDBACK_STATUS enum values
     */
    const CLIENT_INTERVIEW_FEEDBACK_FEEDBACK_STATUS = [
        'SUCCESSFUL' => 'successful',
        'UNSUCCESSFUL' => 'unsuccessful',
        'KEEP_IN_VIEW' => 'keep_in_view',
    ];

    /**
     * CLIENT_INTERVIEWS_INTERVIEW_TYPE enum values
     */
    const CLIENT_INTERVIEWS_INTERVIEW_TYPE = [
        'PHYSICAL' => 'physical',
        'ONLINE' => 'online',
    ];

    /**
     * CLIENT_INTERVIEWS_STATUS enum values
     */
    const CLIENT_INTERVIEWS_STATUS = [
        'SCHEDULED' => 'scheduled',
        'COMPLETED' => 'completed',
        'CANCELLED' => 'cancelled',
        'RESCHEDULED' => 'rescheduled',
    ];

    /**
     * CLIENTS_PAY_CALCULATION_BASIS enum values
     */
    const CLIENTS_PAY_CALCULATION_BASIS = [
        'WORKING_DAYS' => 'working_days',
        'CALENDAR_DAYS' => 'calendar_days',
    ];

    /**
     * CLIENTS_STATUS enum values
     */
    const CLIENTS_STATUS = [
        'ACTIVE' => 'active',
        'INACTIVE' => 'inactive',
        'SUSPENDED' => 'suspended',
    ];

    /**
     * EMOLUMENT_COMPONENTS_STATUS enum values
     */
    const EMOLUMENT_COMPONENTS_STATUS = [
        'BENEFIT' => 'benefit',
        'REGULAR' => 'regular',
    ];

    /**
     * EMOLUMENT_COMPONENTS_TYPE enum values
     */
    const EMOLUMENT_COMPONENTS_TYPE = [
        'FIXED_ALLOWANCE' => 'fixed_allowance',
        'VARIABLE_ALLOWANCE' => 'variable_allowance',
    ];

    /**
     * EMOLUMENT_COMPONENTS_CLASS enum values
     */
    const EMOLUMENT_COMPONENTS_CLASS = [
        'CASH_ITEM' => 'cash_item',
        'NON_CASH_ITEM' => 'non_cash_item',
    ];

    /**
     * EMOLUMENT_COMPONENTS_CATEGORY enum values
     */
    const EMOLUMENT_COMPONENTS_CATEGORY = [
        'BASIC' => 'basic',
        'ALLOWANCE' => 'allowance',
        'DEDUCTION' => 'deduction',
        'BENEFIT' => 'benefit',
    ];

    /**
     * EMOLUMENT_COMPONENTS_CALCULATION_METHOD enum values
     */
    const EMOLUMENT_COMPONENTS_CALCULATION_METHOD = [
        'FIXED' => 'fixed',
        'PERCENTAGE' => 'percentage',
        'FORMULA' => 'formula',
    ];

    /**
     * GENERATED_INVOICES_INVOICE_TYPE enum values
     */
    const GENERATED_INVOICES_INVOICE_TYPE = [
        'WITH_SCHEDULE' => 'with_schedule',
        'WITHOUT_SCHEDULE' => 'without_schedule',
    ];

    /**
     * GENERATED_INVOICES_STATUS enum values
     */
    const GENERATED_INVOICES_STATUS = [
        'DRAFT' => 'draft',
        'GENERATED' => 'generated',
        'SENT' => 'sent',
        'PAID' => 'paid',
    ];

    /**
     * INTERVIEW_INVITATIONS_STATUS enum values
     */
    const INTERVIEW_INVITATIONS_STATUS = [
        'SENT' => 'sent',
        'PENDING' => 'pending',
        'ACCEPTED' => 'accepted',
        'DECLINED' => 'declined',
        'EXPIRED' => 'expired',
    ];

    /**
     * INTERVIEW_SCHEDULES_INTERVIEW_TYPE enum values
     */
    const INTERVIEW_SCHEDULES_INTERVIEW_TYPE = [
        'INITIAL' => 'initial',
        'TECHNICAL' => 'technical',
        'CLIENT_MEETING' => 'client_meeting',
        'FINAL' => 'final',
    ];

    /**
     * INTERVIEW_SCHEDULES_INTERVIEW_MODE enum values
     */
    const INTERVIEW_SCHEDULES_INTERVIEW_MODE = [
        'VIDEO' => 'video',
        'PHONE' => 'phone',
        'IN_PERSON' => 'in_person',
    ];

    /**
     * INTERVIEW_SCHEDULES_STATUS enum values
     */
    const INTERVIEW_SCHEDULES_STATUS = [
        'SCHEDULED' => 'scheduled',
        'IN_PROGRESS' => 'in_progress',
        'COMPLETED' => 'completed',
        'CANCELLED' => 'cancelled',
        'RESCHEDULED' => 'rescheduled',
    ];

    /**
     * INTERVIEW_SCHEDULES_OUTCOME enum values
     */
    const INTERVIEW_SCHEDULES_OUTCOME = [
        'PASSED' => 'passed',
        'FAILED' => 'failed',
        'PENDING' => 'pending',
    ];

    /**
     * INVOICE_TEMPLATES_ATTENDANCE_CALCULATION_METHOD enum values
     */
    const INVOICE_TEMPLATES_ATTENDANCE_CALCULATION_METHOD = [
        'WORKING_DAYS' => 'working_days',
        'CALENDAR_DAYS' => 'calendar_days',
    ];

    /**
     * JOB_INTERVIEWS_STATUS enum values
     */
    const JOB_INTERVIEWS_STATUS = [
        'SCHEDULED' => 'scheduled',
        'IN_PROGRESS' => 'in_progress',
        'COMPLETED' => 'completed',
        'CANCELLED' => 'cancelled',
        'RESCHEDULED' => 'rescheduled',
    ];

    /**
     * JOB_INTERVIEWS_RECOMMENDATION enum values
     */
    const JOB_INTERVIEWS_RECOMMENDATION = [
        'HIRE' => 'hire',
        'REJECT' => 'reject',
        'CONSIDER' => 'consider',
        'PENDING' => 'pending',
    ];

    /**
     * JOB_STRUCTURES_CONTRACT_TYPE enum values
     */
    const JOB_STRUCTURES_CONTRACT_TYPE = [
        'EMPLOYMENT' => 'employment',
        'SERVICE' => 'service',
    ];

    /**
     * JOB_STRUCTURES_CONTRACT_NATURE enum values
     */
    const JOB_STRUCTURES_CONTRACT_NATURE = [
        'AT_WILL' => 'at_will',
        'TENURED' => 'tenured',
    ];

    /**
     * LEAVE_APPLICATIONS_STATUS enum values
     */
    const LEAVE_APPLICATIONS_STATUS = [
        'PENDING' => 'pending',
        'APPROVED' => 'approved',
        'REJECTED' => 'rejected',
    ];

    /**
     * OFFER_LETTER_TEMPLATES_STATUS enum values
     */
    const OFFER_LETTER_TEMPLATES_STATUS = [
        'DRAFT' => 'draft',
        'ACTIVE' => 'active',
        'ARCHIVED' => 'archived',
    ];

    /**
     * OFFER_RESPONSES_RESPONSE_TYPE enum values
     */
    const OFFER_RESPONSES_RESPONSE_TYPE = [
        'ACCEPTED' => 'accepted',
        'REJECTED' => 'rejected',
    ];

    /**
     * PAY_STRUCTURE_TYPES_CONTRACT_TYPE enum values
     */
    const PAY_STRUCTURE_TYPES_CONTRACT_TYPE = [
        'EMPLOYMENT' => 'employment',
        'SERVICE' => 'service',
    ];

    /**
     * PAY_STRUCTURE_TYPES_CONTRACT_NATURE enum values
     */
    const PAY_STRUCTURE_TYPES_CONTRACT_NATURE = [
        'AT_WILL' => 'at_will',
        'TENURED' => 'tenured',
    ];

    /**
     * RECRUITMENT_APPLICATIONS_BACKUP_STATUS enum values
     */
    const RECRUITMENT_APPLICATIONS_BACKUP_STATUS = [
        'PENDING' => 'pending',
        'REVIEWING' => 'reviewing',
        'SHORTLISTED' => 'shortlisted',
        'INTERVIEWED' => 'interviewed',
        'OFFERED' => 'offered',
        'HIRED' => 'hired',
        'REJECTED' => 'rejected',
        'WITHDRAWN' => 'withdrawn',
    ];

    /**
     * RECRUITMENT_APPLICATIONS_BACKUP_APPLICATION_SOURCE enum values
     */
    const RECRUITMENT_APPLICATIONS_BACKUP_APPLICATION_SOURCE = [
        'WEBSITE' => 'website',
        'REFERRAL' => 'referral',
        'AGENCY' => 'agency',
        'SOCIAL_MEDIA' => 'social_media',
        'OTHER' => 'other',
    ];

    /**
     * RECRUITMENT_REQUESTS_STATUS enum values
     */
    const RECRUITMENT_REQUESTS_STATUS = [
        'ACTIVE' => 'active',
        'CLOSED' => 'closed',
        'CANCELLED' => 'cancelled',
        'ON_HOLD' => 'on_hold',
    ];

    /**
     * RECRUITMENT_REQUESTS_GENDER_REQUIREMENT enum values
     */
    const RECRUITMENT_REQUESTS_GENDER_REQUIREMENT = [
        'MALE' => 'male',
        'FEMALE' => 'female',
        'ANY' => 'any',
    ];

    /**
     * RECRUITMENT_REQUESTS_RELIGION_REQUIREMENT enum values
     */
    const RECRUITMENT_REQUESTS_RELIGION_REQUIREMENT = [
        'CHRISTIANITY' => 'christianity',
        'ISLAM' => 'islam',
        'ANY' => 'any',
    ];

    /**
     * RECRUITMENT_REQUESTS_SOL_SERVICE_TYPE enum values
     */
    const RECRUITMENT_REQUESTS_SOL_SERVICE_TYPE = [
        'MSS' => 'MSS',
        'RS' => 'RS',
        'DSS' => 'DSS',
    ];

    /**
     * RECRUITMENT_REQUESTS_PRIORITY_LEVEL enum values
     */
    const RECRUITMENT_REQUESTS_PRIORITY_LEVEL = [
        'LOW' => 'low',
        'MEDIUM' => 'medium',
        'HIGH' => 'high',
        'URGENT' => 'urgent',
    ];

    /**
     * RECRUITMENT_REQUESTS_CLOSURE_REASON enum values
     */
    const RECRUITMENT_REQUESTS_CLOSURE_REASON = [
        'FULFILLED' => 'fulfilled',
        'EXPIRED' => 'expired',
    ];

    /**
     * SOL_OFFICES_CONTROL_TYPE enum values
     */
    const SOL_OFFICES_CONTROL_TYPE = [
        'LGA' => 'lga',
        'STATE' => 'state',
    ];

    /**
     * STAFF_GENDER enum values
     */
    const STAFF_GENDER = [
        'MALE' => 'male',
        'FEMALE' => 'female',
    ];

    /**
     * STAFF_APPOINTMENT_STATUS enum values
     */
    const STAFF_APPOINTMENT_STATUS = [
        'PROBATION' => 'probation',
        'CONFIRMED' => 'confirmed',
        'CONTRACT' => 'contract',
        'INTERN' => 'intern',
    ];

    /**
     * STAFF_EMPLOYMENT_TYPE enum values
     */
    const STAFF_EMPLOYMENT_TYPE = [
        'FULL_TIME' => 'full_time',
        'PART_TIME' => 'part_time',
        'CONTRACT' => 'contract',
        'INTERN' => 'intern',
    ];

    /**
     * STAFF_STATUS enum values
     */
    const STAFF_STATUS = [
        'ACTIVE' => 'active',
        'INACTIVE' => 'inactive',
        'TERMINATED' => 'terminated',
        'RESIGNED' => 'resigned',
        'ON_LEAVE' => 'on_leave',
    ];

    /**
     * STAFF_ONBOARDING_METHOD enum values
     */
    const STAFF_ONBOARDING_METHOD = [
        'FROM_CANDIDATE' => 'from_candidate',
        'MANUAL_ENTRY' => 'manual_entry',
        'BULK_UPLOAD' => 'bulk_upload',
    ];

    /**
     * STAFF_BANKING_PAYMENT_MODE enum values
     */
    const STAFF_BANKING_PAYMENT_MODE = [
        'CASH' => 'cash',
        'BANK_TRANSFER' => 'bank_transfer',
        'CHEQUE' => 'cheque',
    ];

    /**
     * STAFF_BANKING_ENTITLED_TO_OT enum values
     */
    const STAFF_BANKING_ENTITLED_TO_OT = [
        'YES' => 'yes',
        'NO' => 'no',
    ];

    /**
     * STAFF_BANKING_PENSION_DEDUCTION enum values
     */
    const STAFF_BANKING_PENSION_DEDUCTION = [
        'YES' => 'yes',
        'NO' => 'no',
    ];

    /**
     * STAFF_EMERGENCY_CONTACTS_CONTACT_TYPE enum values
     */
    const STAFF_EMERGENCY_CONTACTS_CONTACT_TYPE = [
        'EMERGENCY' => 'emergency',
        'NEXT_OF_KIN' => 'next_of_kin',
        'FAMILY' => 'family',
        'REFEREE' => 'referee',
    ];

    /**
     * STAFF_EMERGENCY_CONTACTS_GENDER enum values
     */
    const STAFF_EMERGENCY_CONTACTS_GENDER = [
        'MALE' => 'male',
        'FEMALE' => 'female',
    ];

    /**
     * STAFF_PERSONAL_INFO_MARITAL_STATUS enum values
     */
    const STAFF_PERSONAL_INFO_MARITAL_STATUS = [
        'SINGLE' => 'single',
        'MARRIED' => 'married',
        'DIVORCED' => 'divorced',
        'WIDOWED' => 'widowed',
    ];

    /**
     * STAFF_PERSONAL_INFO_BLOOD_GROUP enum values
     */
    const STAFF_PERSONAL_INFO_BLOOD_GROUP = [
        'A+' => 'A+',
        'A_' => 'A-',
        'B+' => 'B+',
        'B_' => 'B-',
        'AB+' => 'AB+',
        'AB_' => 'AB-',
        'O+' => 'O+',
        'O_' => 'O-',
    ];

    /**
     * STATES_LGAS_ZONE enum values
     */
    const STATES_LGAS_ZONE = [
        'NORTH_CENTRAL' => 'north_central',
        'NORTH_EAST' => 'north_east',
        'NORTH_WEST' => 'north_west',
        'SOUTH_EAST' => 'south_east',
        'SOUTH_SOUTH' => 'south_south',
        'SOUTH_WEST' => 'south_west',
    ];

    /**
     * TEST_ASSIGNMENTS_STATUS enum values
     */
    const TEST_ASSIGNMENTS_STATUS = [
        'PENDING' => 'pending',
        'IN_PROGRESS' => 'in_progress',
        'COMPLETED' => 'completed',
        'EXPIRED' => 'expired',
    ];

    /**
     * TEST_QUESTIONS_TYPE enum values
     */
    const TEST_QUESTIONS_TYPE = [
        'MULTIPLE_CHOICE' => 'multiple_choice',
        'TRUE_FALSE' => 'true_false',
        'SHORT_ANSWER' => 'short_answer',
    ];

    /**
     * TEST_RESULTS_RESULT_STATUS enum values
     */
    const TEST_RESULTS_RESULT_STATUS = [
        'PASSED' => 'passed',
        'FAILED' => 'failed',
    ];

    /**
     * TESTS_STATUS enum values
     */
    const TESTS_STATUS = [
        'DRAFT' => 'draft',
        'ACTIVE' => 'active',
        'ARCHIVED' => 'archived',
    ];

    /**
     * USERS_USER_TYPE enum values
     */
    const USERS_USER_TYPE = [
        'CANDIDATE' => 'candidate',
        'STAFF' => 'staff',
        'ADMIN' => 'admin',
        'CLIENT' => 'client',
    ];

    // ============================================
    // TABLE METADATA
    // ============================================

    /**
     * Table metadata information
     */
    const TABLE_METADATA = [
        'ATTENDANCE_RECORDS' => [
            'table_name' => 'attendance_records',
            'column_count' => 30,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'ATTENDANCE_UPLOADS' => [
            'table_name' => 'attendance_uploads',
            'column_count' => 24,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'AUDIT_LOGS' => [
            'table_name' => 'audit_logs',
            'column_count' => 13,
            'has_timestamps' => false,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'BOARDING_REQUESTS' => [
            'table_name' => 'boarding_requests',
            'column_count' => 17,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'BOARDING_TIMELINE' => [
            'table_name' => 'boarding_timeline',
            'column_count' => 9,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'CANDIDATE_DOCUMENTS' => [
            'table_name' => 'candidate_documents',
            'column_count' => 8,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_EDUCATION' => [
            'table_name' => 'candidate_education',
            'column_count' => 12,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_EMERGENCY_CONTACTS' => [
            'table_name' => 'candidate_emergency_contacts',
            'column_count' => 16,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_EXPERIENCE' => [
            'table_name' => 'candidate_experience',
            'column_count' => 12,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_JOB_APPLICATIONS' => [
            'table_name' => 'candidate_job_applications',
            'column_count' => 18,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_PRIMARY_EDUCATION' => [
            'table_name' => 'candidate_primary_education',
            'column_count' => 7,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_PROFILES' => [
            'table_name' => 'candidate_profiles',
            'column_count' => 28,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_SECONDARY_EDUCATION' => [
            'table_name' => 'candidate_secondary_education',
            'column_count' => 7,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATE_TERTIARY_EDUCATION' => [
            'table_name' => 'candidate_tertiary_education',
            'column_count' => 7,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CANDIDATES' => [
            'table_name' => 'candidates',
            'column_count' => 13,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'CLIENT_CONTRACTS' => [
            'table_name' => 'client_contracts',
            'column_count' => 12,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'CLIENT_INTERVIEW_FEEDBACK' => [
            'table_name' => 'client_interview_feedback',
            'column_count' => 9,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CLIENT_INTERVIEWS' => [
            'table_name' => 'client_interviews',
            'column_count' => 16,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CLIENT_STAFF_TYPES' => [
            'table_name' => 'client_staff_types',
            'column_count' => 12,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'CLIENTS' => [
            'table_name' => 'clients',
            'column_count' => 13,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'CONTRACT_PARTICULARS_MASTER' => [
            'table_name' => 'contract_particulars_master',
            'column_count' => 9,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'EMOLUMENT_COMPONENTS' => [
            'table_name' => 'emolument_components',
            'column_count' => 19,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'GENERATED_INVOICES' => [
            'table_name' => 'generated_invoices',
            'column_count' => 21,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'INTERVIEW_INVITATIONS' => [
            'table_name' => 'interview_invitations',
            'column_count' => 16,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'INTERVIEW_SCHEDULES' => [
            'table_name' => 'interview_schedules',
            'column_count' => 19,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'INVOICE_LINE_ITEMS' => [
            'table_name' => 'invoice_line_items',
            'column_count' => 19,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'INVOICE_TEMPLATES' => [
            'table_name' => 'invoice_templates',
            'column_count' => 22,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'JOB_CATEGORIES' => [
            'table_name' => 'job_categories',
            'column_count' => 7,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'JOB_INTERVIEWS' => [
            'table_name' => 'job_interviews',
            'column_count' => 14,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'JOB_STRUCTURES' => [
            'table_name' => 'job_structures',
            'column_count' => 13,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'LEAVE_APPLICATIONS' => [
            'table_name' => 'leave_applications',
            'column_count' => 12,
            'has_timestamps' => false,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'LEAVE_TYPES' => [
            'table_name' => 'leave_types',
            'column_count' => 5,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'OFFER_LETTER_TEMPLATES' => [
            'table_name' => 'offer_letter_templates',
            'column_count' => 17,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'OFFER_RESPONSES' => [
            'table_name' => 'offer_responses',
            'column_count' => 10,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'PAY_GRADE_STRUCTURES' => [
            'table_name' => 'pay_grade_structures',
            'column_count' => 17,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'PAY_STRUCTURE_TYPES' => [
            'table_name' => 'pay_structure_types',
            'column_count' => 11,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'PERMISSIONS' => [
            'table_name' => 'permissions',
            'column_count' => 7,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'RECRUITMENT_APPLICATIONS_BACKUP' => [
            'table_name' => 'recruitment_applications_backup',
            'column_count' => 14,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'RECRUITMENT_REQUESTS' => [
            'table_name' => 'recruitment_requests',
            'column_count' => 38,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'ROLE_PERMISSIONS' => [
            'table_name' => 'role_permissions',
            'column_count' => 5,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'ROLES' => [
            'table_name' => 'roles',
            'column_count' => 8,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'SERVICE_LOCATIONS' => [
            'table_name' => 'service_locations',
            'column_count' => 25,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'SERVICE_REQUESTS' => [
            'table_name' => 'service_requests',
            'column_count' => 10,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'SOL_OFFICES' => [
            'table_name' => 'sol_offices',
            'column_count' => 18,
            'has_timestamps' => true,
            'has_soft_deletes' => true,
            'primary_key' => null,
        ],
        'STAFF' => [
            'table_name' => 'staff',
            'column_count' => 39,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'STAFF_BANKING' => [
            'table_name' => 'staff_banking',
            'column_count' => 12,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_BULK_IMPORT_TEMP' => [
            'table_name' => 'staff_bulk_import_temp',
            'column_count' => 118,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_EDUCATION' => [
            'table_name' => 'staff_education',
            'column_count' => 13,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_EMERGENCY_CONTACTS' => [
            'table_name' => 'staff_emergency_contacts',
            'column_count' => 14,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_EXPERIENCE' => [
            'table_name' => 'staff_experience',
            'column_count' => 12,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_GUARANTORS' => [
            'table_name' => 'staff_guarantors',
            'column_count' => 13,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_LEGAL_IDS' => [
            'table_name' => 'staff_legal_ids',
            'column_count' => 10,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_PERSONAL_INFO' => [
            'table_name' => 'staff_personal_info',
            'column_count' => 18,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_REFERENCES' => [
            'table_name' => 'staff_references',
            'column_count' => 9,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STAFF_ROLES' => [
            'table_name' => 'staff_roles',
            'column_count' => 7,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'STATES_LGAS' => [
            'table_name' => 'states_lgas',
            'column_count' => 10,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'SYSTEM_PREFERENCES' => [
            'table_name' => 'system_preferences',
            'column_count' => 10,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => null,
        ],
        'TEST_ASSIGNMENTS' => [
            'table_name' => 'test_assignments',
            'column_count' => 13,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'TEST_QUESTIONS' => [
            'table_name' => 'test_questions',
            'column_count' => 11,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'TEST_RESULTS' => [
            'table_name' => 'test_results',
            'column_count' => 15,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'TESTS' => [
            'table_name' => 'tests',
            'column_count' => 14,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
        'USERS' => [
            'table_name' => 'users',
            'column_count' => 14,
            'has_timestamps' => true,
            'has_soft_deletes' => false,
            'primary_key' => 'id',
        ],
    ];

    // ============================================
    // HELPER METHODS
    // ============================================

    /**
     * Get all field names for a table
     */
    public static function getTableFields(string $tableName): array
    {
        $constantName = strtoupper($tableName);
        return constant('self::' . $constantName) ?? [];
    }

    /**
     * Get field name by constant key
     */
    public static function getField(string $tableName, string $fieldKey): ?string
    {
        $fields = self::getTableFields($tableName);
        return $fields[$fieldKey] ?? null;
    }
}
